#include <define.h>

SUBROUTINE Aggregation_LakeSoilC ( &
      gland, dir_rawdata, dir_model_landdata, lc_year)

!-----------------------------------------------------------------------
! !DESCRIPTION:
!  Aggregate lake-sediment organic carbon for Methane lake production.
!
!  Expected optional raw dataset:
!    1) <dir_rawdata>/lake_soilc.nc, or
!    2) <dir_rawdata>/soil/lake_soilc.nc
!  variable: lake_soilc(soil, lon, lat) [gC/m3]
!
!  If no raw dataset is present, derive a deterministic fallback from the
!  existing soil organic matter volume fraction generated by
!  Aggregation_SoilParameters:
!
!     lake_soilc [gC/m3] = 580 [gC/kg OM] * 130 [kg OM/m3] * vf_om [-]
!
!  The 130 kg OM/m3 reference matches the BGC organic_max initialization.
!  This keeps the fallback in mksrfdata rather than in runtime methane physics.
!-----------------------------------------------------------------------

   USE MOD_Precision
   USE MOD_Vars_Global, only: nl_soil, spval
   USE MOD_Namelist
   USE MOD_SPMD_Task
   USE MOD_Grid
   USE MOD_LandPatch
   USE MOD_NetCDFVector
   USE MOD_NetCDFBlock
#ifdef RangeCheck
   USE MOD_RangeCheck
#endif
   USE MOD_AggregationRequestData
   USE MOD_Utils

   IMPLICIT NONE

   integer, intent(in) :: lc_year
   type(grid_type),  intent(in) :: gland
   character(len=*), intent(in) :: dir_rawdata
   character(len=*), intent(in) :: dir_model_landdata

   character(len=256) :: landdir, lndname, cyear
   character(len=256) :: c
   integer :: ipatch, L, j, nsl, src_layer
   logical :: raw_exists

   type(block_data_real8_3d) :: lake_soilc_grid
   real(r8), allocatable :: lake_soilc_patches(:,:), lake_soilc_one(:,:)
   real(r8), allocatable :: vf_om_s_patches(:)
   real(r8), parameter :: organic_max_default = 130._r8 ! kg OM/m3, BGC default
   real(r8), parameter :: carbon_per_kg_om = 580._r8    ! gC/kg OM
#ifdef SrfdataDiag
   ! No gridded diagnostic is written here because srfdata_map_and_write is
   ! scalar-patch oriented; history/restart expose the 3-D soil-by-patch field.
#endif

      write(cyear,'(i4.4)') lc_year
      landdir = trim(dir_model_landdata) // '/soil/' // trim(cyear)

#ifdef USEMPI
      CALL mpi_barrier (p_comm_glb, p_err)
#endif
      IF (p_is_master) THEN
         write(*,'(/, A)') 'Aggregate lake sediment organic carbon ...'
         CALL system('mkdir -p ' // trim(adjustl(landdir)))
      ENDIF
#ifdef USEMPI
      CALL mpi_barrier (p_comm_glb, p_err)
#endif

      lndname = trim(dir_rawdata)//'/lake_soilc.nc'
      inquire(file=trim(lndname), exist=raw_exists)
      IF (.not. raw_exists) THEN
         lndname = trim(dir_rawdata)//'/soil/lake_soilc.nc'
         inquire(file=trim(lndname), exist=raw_exists)
      ENDIF

      IF (raw_exists) THEN
         IF (p_is_master) write(*,*) '  using raw lake_soilc dataset: ', trim(lndname)
         IF (p_is_io) THEN
            CALL allocate_block_data (gland, lake_soilc_grid, nl_soil)
            CALL ncio_read_block (lndname, 'lake_soilc', gland, nl_soil, lake_soilc_grid)
#ifdef USEMPI
            CALL aggregation_data_daemon (gland, data_r8_3d_in1 = lake_soilc_grid, n1_r8_3d_in1 = nl_soil)
#endif
         ENDIF
      ELSE
         IF (p_is_master) THEN
            write(*,*) '  raw lake_soilc.nc not found; deriving lake_soilc_patches from vf_om_s_l*_patches.'
            write(*,*) '  fallback: lake_soilc = 580 [gC/kg OM] * 130 [kg OM/m3] * vf_om.'
         ENDIF
      ENDIF

      IF (p_is_worker) THEN
         allocate(lake_soilc_patches(nl_soil,numpatch))
         lake_soilc_patches(:,:) = 0._r8

         IF (raw_exists) THEN
            DO ipatch = 1, numpatch
               L = landpatch%settyp(ipatch)
               IF (L == WATERBODY) THEN
                  CALL aggregation_request_data (landpatch, ipatch, gland, &
                     zip = USE_zip_for_aggregation, &
                     data_r8_3d_in1 = lake_soilc_grid, data_r8_3d_out1 = lake_soilc_one, &
                     n1_r8_3d_in1 = nl_soil, lb1_r8_3d_in1 = 1)

                  WHERE (lake_soilc_one < 0._r8) lake_soilc_one = spval
                  DO j = 1, nl_soil
                     lake_soilc_patches(j,ipatch) = median(lake_soilc_one(j,:), size(lake_soilc_one,2), spval)
                     IF (lake_soilc_patches(j,ipatch) == spval) lake_soilc_patches(j,ipatch) = 0._r8
                  ENDDO
               ENDIF
            ENDDO
         ENDIF

#ifdef USEMPI
         IF (raw_exists) CALL aggregation_worker_done ()
#endif
      ENDIF

      IF (.not. raw_exists) THEN
         DO j = 1, nl_soil
            IF (j == 1) THEN
               src_layer = 1
            ELSE
               src_layer = min(8, j - 1)
            ENDIF
            write(c,'(i1)') src_layer

            lndname = trim(landdir)//'/vf_om_s_l'//trim(c)//'_patches.nc'
            CALL ncio_read_vector (lndname, 'vf_om_s_l'//trim(c)//'_patches', &
               landpatch, vf_om_s_patches, defval = 0._r8)

            IF (p_is_worker) THEN
               DO ipatch = 1, numpatch
                  IF (landpatch%settyp(ipatch) == WATERBODY .and. vf_om_s_patches(ipatch) > 0._r8) THEN
                     lake_soilc_patches(j,ipatch) = carbon_per_kg_om * organic_max_default * vf_om_s_patches(ipatch)
                  ELSE
                     lake_soilc_patches(j,ipatch) = 0._r8
                  ENDIF
               ENDDO
            ENDIF
         ENDDO
         IF (allocated(vf_om_s_patches)) deallocate(vf_om_s_patches)
      ENDIF

#ifdef USEMPI
      CALL mpi_barrier (p_comm_glb, p_err)
#endif

#ifdef RangeCheck
      CALL check_vector_data ('lake_soilc_patches [gC/m3]', lake_soilc_patches)
#endif

      lndname = trim(landdir)//'/lake_soilc_patches.nc'
      CALL ncio_create_file_vector (lndname, landpatch)
      CALL ncio_define_dimension_vector (lndname, landpatch, 'soil', nl_soil)
      CALL ncio_define_dimension_vector (lndname, landpatch, 'patch')
      CALL ncio_write_vector (lndname, 'lake_soilc_patches', 'soil', nl_soil, 'patch', &
         landpatch, lake_soilc_patches, DEF_Srfdata_CompressLevel)

      IF (p_is_worker) THEN
         deallocate(lake_soilc_patches)
      ENDIF

END SUBROUTINE Aggregation_LakeSoilC
