#include <define.h>

#if (defined TRACER) && (defined BGC)
MODULE MOD_Tracer_Reactive_Methane_pH

!-----------------------------------------------------------------------
! DESCRIPTION:
!   Loads per-patch CoLM PHH2O (pH in H2O) surface data and exposes
!   column-mean soil pH to the methane physics through BgcLink.
!
! INPUT FILES (under DEF_dir_rawdata/soil/):
!   PHH2O1.nc  - top 4 soil layers (depth bottoms 4.5, 9.1, 16.6, 28.9 cm)
!   PHH2O2.nc  - bottom 4 soil layers (depth bottoms to 229.6 cm)
!   Variable PHH2O(depth, lat, lon), byte type, units "1/10" (pH x 10),
!   missing_value = -100.  30 arcsec global, lat -56..84, lon -180..180.
!
! RECOMMENDED INIT ALGORITHM:
!   mksrfdata precomputes a native-resolution patch-level field:
!      <landdata>/soil/<lc_year>/methane_ph_patches.nc
!      variable methane_ph_patches(patch)
!   colm.x reads only this patch vector.  This avoids runtime reads and
!   broadcasts of the 2.8 GB global PHH2O raw file.
!
! Runtime raw-PHH2O reads were removed: use the patch-vector file above.
! Fallback pH = 6.2 (neutral, Dunfield optimum) when that vector is absent.
!
! RUNTIME:
!   FUNCTION get_ph_for_patch(ipatch) returns the per-patch column-mean
!   soil pH (top 30 cm).  BgcLink calls this instead of the hardcoded
!   pH = 6.2.  pH factor only applied if DEF_METHANE%usephfact = .true.
!
! Notes:
!   - Column-mean over top 4 layers (0-29 cm) is what matters for
!     methanogenesis: production peaks in the shallow saturated layer
!     near the water table top.  Deeper PHH2O2.nc not used here; future
!     work can add per-layer pH if needed.
!   - Nearest-pixel mapping is fine since CoLM patches (~10-50 km) are
!     much larger than the 30 arc-sec PHH2O grid (~1 km).
!
!-----------------------------------------------------------------------

   USE MOD_Precision
   USE MOD_SPMD_Task

   IMPLICIT NONE
   SAVE
   PRIVATE

   ! Per-patch column-mean soil pH (top 30 cm); units = real pH (3-10)
   real(r8), allocatable, public :: methane_ph_patch(:)
   logical, public :: ph_active = .false.

   ! Fallback pH used when data is missing or patch cannot be matched.
   ! 6.2 is the Dunfield 1993 optimum (pH_fact_methane peaks at 1.0).
   real(r8), parameter, public :: methane_ph_fallback = 6.2_r8

   PUBLIC :: allocate_methane_ph
   PUBLIC :: deallocate_methane_ph
   PUBLIC :: read_methane_ph_patch
   PUBLIC :: get_ph_for_patch

CONTAINS

   SUBROUTINE allocate_methane_ph(numpatch)
      integer, intent(in) :: numpatch
      IF (allocated(methane_ph_patch)) RETURN
      ! Keep zero-length arrays allocated on ranks with numpatch==0.  pH
      ! vector I/O is collective, while patch accessors are bounds-guarded.
      allocate(methane_ph_patch(numpatch))
      methane_ph_patch(:) = methane_ph_fallback
   END SUBROUTINE allocate_methane_ph

   SUBROUTINE deallocate_methane_ph()
      IF (allocated(methane_ph_patch)) deallocate(methane_ph_patch)
      ph_active = .false.
   END SUBROUTINE deallocate_methane_ph

   SUBROUTINE read_methane_ph_patch(file_ph_patch, numpatch)
      ! Read the patch-level pH vector generated by mksrfdata
      ! (Aggregation_MethanePH).  If the vector file/variable is missing,
      ! ncio_read_vector uses the neutral fallback and the model continues.
#ifdef USEMPI
      USE MPI
#endif
      USE MOD_NetCDFVector, only: ncio_read_vector
      USE MOD_LandPatch,    only: landpatch
      character(len=*), intent(in) :: file_ph_patch
      integer, intent(in) :: numpatch
      logical :: has_nonfallback_ph
      integer :: n_nonfallback, n_local_patch
      integer :: n_global_nonfallback, n_global_patch
      integer :: local_has_i, global_has_i
      real(r8) :: ph_min, ph_max
      real(r8) :: ph_min_global, ph_max_global

      IF (numpatch > 0 .and. .not. allocated(methane_ph_patch)) CALL allocate_methane_ph(numpatch)
      IF (allocated(methane_ph_patch)) methane_ph_patch(:) = methane_ph_fallback

      CALL ncio_read_vector(file_ph_patch, 'methane_ph_patches', landpatch, &
         methane_ph_patch, defval = methane_ph_fallback)

      IF (allocated(methane_ph_patch)) THEN
         WHERE (methane_ph_patch < 2._r8 .or. methane_ph_patch > 10._r8)
            methane_ph_patch = methane_ph_fallback
         END WHERE
      ENDIF
      has_nonfallback_ph = .false.
      IF (allocated(methane_ph_patch)) &
         has_nonfallback_ph = any(abs(methane_ph_patch - methane_ph_fallback) > 1.e-12_r8)

      n_local_patch = 0
      n_nonfallback = 0
      local_has_i = 0
      ph_min = huge(1._r8)
      ph_max = -huge(1._r8)
      IF (allocated(methane_ph_patch) .and. size(methane_ph_patch) > 0) THEN
         n_local_patch = size(methane_ph_patch)
         n_nonfallback = count(abs(methane_ph_patch - methane_ph_fallback) > 1.e-12_r8)
         IF (n_nonfallback > 0) local_has_i = 1
         ph_min = minval(methane_ph_patch)
         ph_max = maxval(methane_ph_patch)
      ENDIF

      n_global_patch = n_local_patch
      n_global_nonfallback = n_nonfallback
      global_has_i = local_has_i
      ph_min_global = ph_min
      ph_max_global = ph_max
#ifdef USEMPI
      CALL mpi_allreduce (n_local_patch, n_global_patch, 1, MPI_INTEGER, MPI_SUM, p_comm_glb, p_err)
      CALL mpi_allreduce (n_nonfallback, n_global_nonfallback, 1, MPI_INTEGER, MPI_SUM, p_comm_glb, p_err)
      CALL mpi_allreduce (local_has_i, global_has_i, 1, MPI_INTEGER, MPI_MAX, p_comm_glb, p_err)
      CALL mpi_allreduce (ph_min, ph_min_global, 1, MPI_REAL8, MPI_MIN, p_comm_glb, p_err)
      CALL mpi_allreduce (ph_max, ph_max_global, 1, MPI_REAL8, MPI_MAX, p_comm_glb, p_err)
#endif
      ph_active = global_has_i > 0
      IF (n_global_patch <= 0) THEN
         ph_min_global = methane_ph_fallback
         ph_max_global = methane_ph_fallback
      ENDIF

      IF (p_is_master) THEN
         write(6,'(A,L1,A,I0,A,I0,A,F5.2,A,F5.2,A,A)') &
            ' PH-LOAD patch pH: active=', ph_active, ', nonfallback=', n_global_nonfallback, &
            '/', n_global_patch, ', range=[', ph_min_global, ',', ph_max_global, '], file=', trim(file_ph_patch)
      ENDIF
   END SUBROUTINE read_methane_ph_patch

   real(r8) FUNCTION get_ph_for_patch(ipatch)
      integer, intent(in) :: ipatch
      get_ph_for_patch = methane_ph_fallback
      IF (.not. ph_active) RETURN
      IF (.not. allocated(methane_ph_patch)) RETURN
      IF (ipatch < 1 .or. ipatch > size(methane_ph_patch)) RETURN
      get_ph_for_patch = methane_ph_patch(ipatch)
   END FUNCTION get_ph_for_patch

END MODULE MOD_Tracer_Reactive_Methane_pH
#endif
