MODULE CMF_CTRL_MAPS_MOD
!==========================================================
!* PURPOSE: Control CaMa-Flood map/topography data
!
!* CONTAINS:
! -- CMF_MAPS_NMLIST   : configuration from namelist
! -- CMF_RIVMAP_INIT  : read & set river network map 
! -- CMF_TOPO_INIT    : read & set topography
!
! (C) D.Yamazaki & E. Dutra  (U-Tokyo/FCUL)  Aug 2019
!
! Licensed under the Apache License, Version 2.0 (the "License");
!   You may not use this file except in compliance with the License.
!   You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
!
! Unless required by applicable law or agreed to in writing, software distributed under the License is 
!  distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
! See the License for the specific language governing permissions and limitations under the License.
!==========================================================
! shared variables in module
USE PARKIND1,                ONLY: JPIM, JPRB, JPRD, JPRM
USE YOS_CMF_INPUT,           ONLY: LOGNAM, CROUTINGNC
IMPLICIT NONE
SAVE
!*** NAMELIST/NMAP/ from inputnam
CHARACTER(LEN=256)              :: CNEXTXY         !! river network nextxy
CHARACTER(LEN=256)              :: CGRAREA         !! catchment area
CHARACTER(LEN=256)              :: CELEVTN         !! bank top elevation
CHARACTER(LEN=256)              :: CNXTDST         !! distance to next outlet
CHARACTER(LEN=256)              :: CRIVLEN         !! river channel length
CHARACTER(LEN=256)              :: CFLDHGT         !! floodplain elevation profile
CHARACTER(LEN=256)              :: CGRDARE         !! grid area
!* river channel parameters
CHARACTER(LEN=256)              :: CRIVWTH         !! channel width
CHARACTER(LEN=256)              :: CRIVHGT         !! channel depth
CHARACTER(LEN=256)              :: CRIVMAN         !! river manning coefficient
!* optional maps
CHARACTER(LEN=256)              :: CPTHOUT         !! bifurcation channel table
CHARACTER(LEN=256)              :: CGDWDLY         !! Groundwater Delay Parameter
CHARACTER(LEN=256)              :: CMEANSL         !! mean sea level
!* MPI parallelization
CHARACTER(LEN=256)              :: CMPIREG         !! MPI region map
!* netCDF map
LOGICAL                         :: LMAPCDF         !! true for netCDF map input
CHARACTER(LEN=256)              :: CRIVCLINC       !! river map netcdf
CHARACTER(LEN=256)              :: CRIVPARNC       !! river parameter netcdf (WIDTH,HEIGHT, Manning, ground wateer delay)
CHARACTER(LEN=256)              :: CMEANSLNC       !! mean sea level netCDF
CHARACTER(LEN=256)              :: CMPIREGNC       !! MPI region map in netcdf

NAMELIST/NMAP/     CNEXTXY,  CGRAREA,  CELEVTN,  CNXTDST, CRIVLEN, CFLDHGT, CGRDARE, &
                   CRIVWTH,  CRIVHGT,  CRIVMAN,  CPTHOUT, CGDWDLY, CMEANSL, &
                   CMPIREG,  LMAPCDF,  CRIVCLINC,CRIVPARNC,CMEANSLNC,CMPIREGNC,CROUTINGNC


CONTAINS
!####################################################################
! -- CMF_MAP_NMLIST   : configuration from namelist
! -- CMF_RIVMAP_INIT  : read & set river network map 
! -- CMF_TOPO_INIT    : read & set topography
!
!
!####################################################################
SUBROUTINE CMF_MAPS_NMLIST(ROUTING_FILE)
! reed setting from namelist
! -- Called from CMF_DRV_NMLIST
USE YOS_CMF_INPUT,      ONLY: CSETFILE,NSETFILE,LMEANSL,LGDWDLY
USE CMF_UTILS_MOD,      ONLY: INQUIRE_FID
IMPLICIT NONE
CHARACTER(LEN=*),OPTIONAL,INTENT(IN) :: ROUTING_FILE
LOGICAL :: FILE_EXISTS
!================================================
!*** 1. open namelist
WRITE(LOGNAM,*) ""
WRITE(LOGNAM,*) "!---------------------!"

NSETFILE=INQUIRE_FID()
IF( CSETFILE/="NONE" ) OPEN(NSETFILE,FILE=CSETFILE,STATUS="OLD")
IF( CSETFILE/="NONE" ) WRITE(LOGNAM,*) "CMF::MAP_NMLIST: namelist OPEN in unit: ", TRIM(CSETFILE), NSETFILE

!*** 2. default value
CNEXTXY="./nextxy.bin"
CGRAREA="./ctmare.bin"
CELEVTN="./elevtn.bin"
CNXTDST="./nxtdst.bin"
CRIVLEN="./rivlen.bin"
CFLDHGT="./fldhgt.bin"
CGRDARE="./grdare.bin"

CRIVWTH="./rivwth.bin"
CRIVHGT="./rivhgt.bin"
CRIVMAN="./rivman.bin"

CPTHOUT="./bifprm.txt"
CGDWDLY="NONE"
CMEANSL="NONE"

CMPIREG="NONE"
CROUTINGNC="NONE"

LMAPCDF=.FALSE.
CRIVCLINC="NONE"
CRIVPARNC="NONE"
CMEANSLNC="NONE"
CMPIREGNC="NONE"

!*** 3. read namelist
IF( CSETFILE/="NONE" ) REWIND(NSETFILE)
IF( CSETFILE/="NONE" ) READ(NSETFILE,NML=NMAP)
IF( PRESENT(ROUTING_FILE) )THEN
  SELECT CASE(TRIM(ROUTING_FILE))
  CASE('', 'null', 'NULL', 'none', 'NONE')
  CASE DEFAULT
    IF( LEN_TRIM(ROUTING_FILE)>LEN(CROUTINGNC) ) ERROR STOP 'CaMa routing path too long'
    CROUTINGNC=TRIM(ROUTING_FILE)
  END SELECT
ENDIF
IF( CROUTINGNC=='' .OR. CROUTINGNC=='none' .OR. CROUTINGNC=='null' .OR. CROUTINGNC=='NULL' ) &
  CROUTINGNC='NONE'
IF( CROUTINGNC/="NONE" )THEN
#ifdef UseMPI_CMF
  ERROR STOP 'CaMa routing NC does not support UseMPI_CMF decomposition'
#endif
  INQUIRE(FILE=TRIM(CROUTINGNC),EXIST=FILE_EXISTS)
  IF( .NOT.FILE_EXISTS ) ERROR STOP 'CaMa routing NC file missing'
  CALL READ_ROUTING_HEADER_CDF
ENDIF

WRITE(LOGNAM,*)     "=== NAMELIST, NMAP ==="
WRITE(LOGNAM,*)     "CROUTINGNC: ", TRIM(CROUTINGNC)
IF( CROUTINGNC/="NONE" )THEN
  WRITE(LOGNAM,*) "Routing topology and parameters from NC"
ELSEIF( LMAPCDF )THEN
  WRITE(LOGNAM,*)   "CRIVCLINC: ", TRIM(CRIVCLINC)
  WRITE(LOGNAM,*)   "CRIVPARNC: ", TRIM(CRIVPARNC)
  IF( LMEANSL ) THEN
    WRITE(LOGNAM,*) "CMEANSLNC: ", TRIM(CMEANSLNC)
  ENDIF
#ifdef UseMPI_CMF
    WRITE(LOGNAM,*) "CMPIREGNC:   ", TRIM(CMPIREGNC)
#endif
ELSE
  WRITE(LOGNAM,*)   "CNEXTXY:   ", TRIM(CNEXTXY)
  WRITE(LOGNAM,*)   "CGRAREA:   ", TRIM(CGRAREA)
  WRITE(LOGNAM,*)   "CELEVTN:   ", TRIM(CELEVTN)
  WRITE(LOGNAM,*)   "CNXTDST:   ", TRIM(CNXTDST)
  WRITE(LOGNAM,*)   "CRIVLEN:   ", TRIM(CRIVLEN)
  WRITE(LOGNAM,*)   "CFLDHGT:   ", TRIM(CFLDHGT)
  WRITE(LOGNAM,*)   "CGRDARE:   ", TRIM(CGRDARE)

  WRITE(LOGNAM,*)   "CRIVWTH:   ", TRIM(CRIVWTH)
  WRITE(LOGNAM,*)   "CRIVHGT:   ", TRIM(CRIVHGT)
  WRITE(LOGNAM,*)   "CRIVMAN:   ", TRIM(CRIVMAN)

  WRITE(LOGNAM,*)   "CPTHOUT:   ", TRIM(CPTHOUT)
  IF( LGDWDLY )THEN
    WRITE(LOGNAM,*) "CGDWDLY:    ",TRIM(CGDWDLY)
  ENDIF
  IF( LMEANSL )THEN
    WRITE(LOGNAM,*) "CMEANSL:   ", TRIM(CMEANSL)
  ENDIF
#ifdef UseMPI_CMF
    WRITE(LOGNAM,*) "CMPIREG:   ", TRIM(CMPIREG)
#endif
ENDIF

IF( CSETFILE/="NONE" ) CLOSE(NSETFILE)

WRITE(LOGNAM,*) "CMF::MAP_NMLIST: end"

END SUBROUTINE CMF_MAPS_NMLIST
!####################################################################





SUBROUTINE READ_ROUTING_HEADER_CDF
USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
USE YOS_CMF_INPUT, ONLY: NX,NY,NLFP,NXIN,NYIN,INPN,WEST,EAST,NORTH,SOUTH
#ifdef UseCDF_CMF
USE CMF_UTILS_MOD, ONLY: NCERROR
USE NETCDF
#endif
IMPLICIT NONE
#ifdef UseCDF_CMF
INTEGER(KIND=JPIM) :: NCID,DIMID,VARID,STATUS
INTEGER(KIND=JPIM) :: DIMIDS2(2),NSEQTMP,LEN1,LEN2,SEQDIM

CALL NCERROR(NF90_OPEN(TRIM(CROUTINGNC),NF90_NOWRITE,NCID),'opening '//TRIM(CROUTINGNC))
STATUS=NF90_INQ_DIMID(NCID,'nx',DIMID)
IF( STATUS==NF90_NOERR )THEN
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=NX),'reading nx dimension')
ELSE
  CALL NCERROR(NF90_INQ_VARID(NCID,'lon',VARID),'getting lon id')
  CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS2(1:1)),'reading lon dimensions')
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(1),LEN=NX),'reading lon length')
ENDIF
STATUS=NF90_INQ_DIMID(NCID,'ny',DIMID)
IF( STATUS==NF90_NOERR )THEN
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=NY),'reading ny dimension')
ELSE
  CALL NCERROR(NF90_INQ_VARID(NCID,'lat',VARID),'getting lat id')
  CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS2(1:1)),'reading lat dimensions')
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(1),LEN=NY),'reading lat length')
ENDIF
CALL NCERROR(NF90_INQ_VARID(NCID,'seq_x',VARID),'getting seq_x id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS2(1:1)),'reading seq_x dimensions')
CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(1),LEN=NSEQTMP),'reading seq_x length')
SEQDIM=DIMIDS2(1)
STATUS=NF90_INQ_DIMID(NCID,'nlfp',DIMID)
IF( STATUS==NF90_NOERR )THEN
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=NLFP),'reading nlfp dimension')
ELSE
  CALL NCERROR(NF90_INQ_VARID(NCID,'topo_fldhgt',VARID),'getting topo_fldhgt id')
  CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS2),'reading topo_fldhgt dimensions')
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(1),LEN=LEN1),'reading topo_fldhgt dimension')
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(2),LEN=LEN2),'reading topo_fldhgt dimension')
  IF( DIMIDS2(1)==SEQDIM .AND. LEN1==NSEQTMP )THEN
    NLFP=LEN2
  ELSEIF( DIMIDS2(2)==SEQDIM .AND. LEN2==NSEQTMP )THEN
    NLFP=LEN1
  ELSE
    ERROR STOP 'CaMa invalid floodplain-height dimensions'
  ENDIF
ENDIF
STATUS=NF90_INQ_DIMID(NCID,'inpn',DIMID)
IF( STATUS==NF90_NOERR )THEN
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=INPN),'reading inpn dimension')
ELSE
  CALL NCERROR(NF90_INQ_VARID(NCID,'inpmat_area',VARID),'getting inpmat_area id')
  CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS2),'reading inpmat_area dimensions')
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(1),LEN=LEN1),'reading inpmat_area dimension')
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(2),LEN=LEN2),'reading inpmat_area dimension')
  IF( DIMIDS2(1)==SEQDIM .AND. LEN1==NSEQTMP )THEN
    INPN=LEN2
  ELSEIF( DIMIDS2(2)==SEQDIM .AND. LEN2==NSEQTMP )THEN
    INPN=LEN1
  ELSE
    ERROR STOP 'CaMa invalid input-matrix dimensions'
  ENDIF
ENDIF
CALL NCERROR(NF90_GET_ATT(NCID,NF90_GLOBAL,'west',WEST),'reading west bound')
CALL NCERROR(NF90_GET_ATT(NCID,NF90_GLOBAL,'east',EAST),'reading east bound')
CALL NCERROR(NF90_GET_ATT(NCID,NF90_GLOBAL,'north',NORTH),'reading north bound')
CALL NCERROR(NF90_GET_ATT(NCID,NF90_GLOBAL,'south',SOUTH),'reading south bound')
CALL NCERROR(NF90_CLOSE(NCID))

IF( NX<=0 .OR. NY<=0 .OR. NLFP<=0 .OR. INPN<=0 ) ERROR STOP 'CaMa invalid routing dimensions'
IF( .NOT.(IEEE_IS_FINITE(WEST) .AND. IEEE_IS_FINITE(EAST) .AND. &
          IEEE_IS_FINITE(NORTH) .AND. IEEE_IS_FINITE(SOUTH)) .OR. &
    EAST<=WEST .OR. NORTH<=SOUTH ) ERROR STOP 'CaMa invalid routing bounds'
NXIN=NX
NYIN=NY
#else
ERROR STOP 'CaMa routing NC requires UseCDF_CMF'
#endif
END SUBROUTINE READ_ROUTING_HEADER_CDF





!####################################################################
SUBROUTINE CMF_RIVMAP_INIT
! read & set river network map 
! -- call from CMF_DRV_INIT
USE YOS_CMF_INPUT,      ONLY: TMPNAM, NX,NY,NLFP, LPTHOUT
USE YOS_CMF_MAP,        ONLY: I2NEXTX,I2NEXTY, I2REGION, REGIONALL,REGIONTHIS, &
                            & I1SEQX, I1SEQY,  I1NEXT,  I2VECTOR, D1LON,    D1LAT,      &
                            & NSEQRIV,NSEQALL, NSEQMAX, NPTHOUT,  NPTHLEV, ROUTING_OLD_TO_NEW
USE YOS_CMF_MAP,        ONLY: I1UPST, I1UPN, I1P_OUT, I1P_OUTN, I1P_INF, I1P_INFN
USE CMF_UTILS_MOD,      ONLY: INQUIRE_FID
IMPLICIT NONE
!================================================
WRITE(LOGNAM,*) ""
WRITE(LOGNAM,*) "!---------------------!"
WRITE(LOGNAM,*) 'CMF::RIVMAP_INIT: river network initialization'

! *** 1. ALLOCATE ARRAYS
ALLOCATE( I2NEXTX(NX,NY) )
ALLOCATE( I2NEXTY(NX,NY) )
ALLOCATE( I2REGION(NX,NY) )
ALLOCATE( D1LON(NX) )
ALLOCATE( D1LAT(NY) )

!============================
!*** 2a. read river network map
WRITE(LOGNAM,*) 'CMF::RIVMAP_INIT: read nextXY & set lat lon'
IF( CROUTINGNC/="NONE" )THEN
#ifdef UseCDF_CMF
  CALL READ_ROUTING_MAP_CDF
#endif
ELSEIF( LMAPCDF )THEN
#ifdef UseCDF_CMF
  CALL READ_MAP_CDF
#endif
ELSE
  CALL READ_MAP_BIN
ENDIF

!*** 2b. calculate river sequence & regions
!============================
!*** 3. conversion 2D map -> 1D vector
IF( CROUTINGNC=="NONE" )THEN
  WRITE(LOGNAM,*) 'CMF::RIVMAP_INIT: calc region'
  CALL CALC_REGION
  WRITE(LOGNAM,*) 'CMF::RIVMAP_INIT: calculate 1d river sequence'
  CALL CALC_1D_SEQ
ENDIF

WRITE(LOGNAM,*) '  NSEQRIV=',NSEQRIV
WRITE(LOGNAM,*) '  NSEQALL=',NSEQALL
WRITE(LOGNAM,*) '  NSEQMAX=',NSEQMAX

!*** 3c. Write Map Data                                       !! used for combining mpi distributed output into one map
IF( REGIONTHIS==1 )THEN
  TMPNAM=INQUIRE_FID()
  OPEN(TMPNAM,FILE='./mapdata.txt',FORM='FORMATTED')
  WRITE(TMPNAM,*) 'NX',        NX
  WRITE(TMPNAM,*) 'NY',        NY
  WRITE(TMPNAM,*) 'NLFP',      NLFP
  WRITE(TMPNAM,*) 'REGIONALL', REGIONALL
  WRITE(TMPNAM,*) 'NSEQMAX',   NSEQMAX
  CLOSE(TMPNAM)
ENDIF

!============================
!*** 4.  bifurcation channel parameters
NPTHOUT=1  !! tentative number
NPTHLEV=1
IF( LPTHOUT )THEN
  WRITE(LOGNAM,*) 'CMF::RIVMAP_INIT: read bifurcation channel setting'
  IF( CROUTINGNC/="NONE" )THEN
#ifdef UseCDF_CMF
    CALL READ_ROUTING_BIF_CDF
#endif
  ELSE
    CALL READ_BIFPARAM
  ENDIF
ENDIF

!DEALLOCATE( I2NEXTX,I2NEXTY,I2REGION )
DEALLOCATE( I2NEXTY,I2REGION )

WRITE(LOGNAM,*) 'CMF::RIVMAP_INIT: end'

CONTAINS
!==========================================================
!+ READ_MAP_BIN
!+ READ_MAP_CDF
!+ CALC_REGION
!+ CALC_1D_SEQ
!+ READ_BIFPRM
!==========================================================
#ifdef UseCDF_CMF
SUBROUTINE READ_ROUTING_MAP_CDF
USE YOS_CMF_INPUT, ONLY: IMIS
USE CMF_UTILS_MOD, ONLY: NCERROR
USE NETCDF
IMPLICIT NONE
INTEGER(KIND=JPIM) :: NCID,VARID,ISEQ,JSEQ,IX,IY,QHEAD,QTAIL,NVISIT,UPNMAX
INTEGER(KIND=JPIM) :: DIMIDS1(1)
INTEGER(KIND=JPIM),ALLOCATABLE :: SEQX_RAW(:),SEQY_RAW(:),NEXT_RAW(:),NUPCALC(:),NUPWORK(:),QUEUE(:),ORDER(:)

CALL NCERROR(NF90_OPEN(TRIM(CROUTINGNC),NF90_NOWRITE,NCID),'opening '//TRIM(CROUTINGNC))
CALL NCERROR(NF90_INQ_VARID(NCID,'seq_x',VARID),'getting seq_x id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS1),'reading seq_x dimensions')
CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS1(1),LEN=NSEQMAX),'reading seq_x length')
IF( NSEQMAX<=0 ) ERROR STOP 'CaMa invalid routing sequence dimension'

ALLOCATE(I1SEQX(NSEQMAX),I1SEQY(NSEQMAX),I1NEXT(NSEQMAX),I2VECTOR(NX,NY))
ALLOCATE(SEQX_RAW(NSEQMAX),SEQY_RAW(NSEQMAX),NEXT_RAW(NSEQMAX))
ALLOCATE(NUPCALC(NSEQMAX),NUPWORK(NSEQMAX),QUEUE(NSEQMAX),ORDER(NSEQMAX))
NUPCALC=0
CALL NCERROR(NF90_INQ_VARID(NCID,'lon',VARID),'getting lon id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,D1LON),'reading lon')
CALL NCERROR(NF90_INQ_VARID(NCID,'lat',VARID),'getting lat id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,D1LAT),'reading lat')
CALL NCERROR(NF90_INQ_VARID(NCID,'seq_x',VARID),'getting seq_x id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,SEQX_RAW),'reading seq_x')
CALL NCERROR(NF90_INQ_VARID(NCID,'seq_y',VARID),'getting seq_y id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,SEQY_RAW),'reading seq_y')
CALL NCERROR(NF90_INQ_VARID(NCID,'seq_next',VARID),'getting seq_next id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,NEXT_RAW),'reading seq_next')
CALL NCERROR(NF90_CLOSE(NCID))

I1SEQX=SEQX_RAW
I1SEQY=SEQY_RAW
I1NEXT=NEXT_RAW
I2NEXTX=IMIS
I2NEXTY=IMIS
I2REGION=IMIS
I2VECTOR=0
REGIONALL=1
NSEQALL=NSEQMAX
DO ISEQ=1,NSEQMAX
  IX=I1SEQX(ISEQ)
  IY=I1SEQY(ISEQ)
  IF( IX<1 .OR. IX>NX .OR. IY<1 .OR. IY>NY ) ERROR STOP 'CaMa routing grid index out of range'
  IF( I2VECTOR(IX,IY)/=0 ) ERROR STOP 'CaMa duplicate routing grid index'
  I2VECTOR(IX,IY)=ISEQ
  I2REGION(IX,IY)=1
ENDDO
DO ISEQ=1,NSEQMAX
  JSEQ=I1NEXT(ISEQ)
  IF( JSEQ>0 )THEN
    IF( JSEQ>NSEQMAX .OR. JSEQ==ISEQ ) ERROR STOP 'CaMa invalid downstream sequence'
    NUPCALC(JSEQ)=NUPCALC(JSEQ)+1
  ENDIF
ENDDO

NSEQRIV=COUNT(I1NEXT>0)
QHEAD=1
QTAIL=0
DO ISEQ=1,NSEQMAX
  IF( NUPCALC(ISEQ)==0 .AND. I1NEXT(ISEQ)>0 )THEN
    QTAIL=QTAIL+1
    QUEUE(QTAIL)=ISEQ
  ENDIF
ENDDO
NVISIT=0
NUPWORK=NUPCALC
DO WHILE( QHEAD<=QTAIL )
  ISEQ=QUEUE(QHEAD)
  QHEAD=QHEAD+1
  NVISIT=NVISIT+1
  ORDER(NVISIT)=ISEQ
  JSEQ=I1NEXT(ISEQ)
  IF( JSEQ>0 )THEN
    NUPWORK(JSEQ)=NUPWORK(JSEQ)-1
    IF( NUPWORK(JSEQ)==0 .AND. I1NEXT(JSEQ)>0 )THEN
      QTAIL=QTAIL+1
      QUEUE(QTAIL)=JSEQ
    ENDIF
  ENDIF
ENDDO
IF( NVISIT/=NSEQRIV ) ERROR STOP 'CaMa routing sequence contains a cycle'
DO ISEQ=1,NSEQMAX
  IF( I1NEXT(ISEQ)<=0 )THEN
    NVISIT=NVISIT+1
    ORDER(NVISIT)=ISEQ
  ENDIF
ENDDO
IF( ALLOCATED(ROUTING_OLD_TO_NEW) ) DEALLOCATE(ROUTING_OLD_TO_NEW)
ALLOCATE(ROUTING_OLD_TO_NEW(NSEQMAX))
DO ISEQ=1,NSEQMAX
  ROUTING_OLD_TO_NEW(ORDER(ISEQ))=ISEQ
ENDDO
DO ISEQ=1,NSEQMAX
  JSEQ=ORDER(ISEQ)
  I1SEQX(ISEQ)=SEQX_RAW(JSEQ)
  I1SEQY(ISEQ)=SEQY_RAW(JSEQ)
  IF( NEXT_RAW(JSEQ)>0 )THEN
    I1NEXT(ISEQ)=ROUTING_OLD_TO_NEW(NEXT_RAW(JSEQ))
  ELSE
    I1NEXT(ISEQ)=NEXT_RAW(JSEQ)
  ENDIF
ENDDO
NUPCALC=0
DO ISEQ=1,NSEQRIV
  JSEQ=I1NEXT(ISEQ)
  NUPCALC(JSEQ)=NUPCALC(JSEQ)+1
ENDDO
UPNMAX=MAX(1,MAXVAL(NUPCALC))
ALLOCATE(I1UPST(NSEQMAX,UPNMAX),I1UPN(NSEQMAX))
I1UPST=-9999
I1UPN=NUPCALC
NUPCALC=0
DO ISEQ=1,NSEQRIV
  JSEQ=I1NEXT(ISEQ)
  NUPCALC(JSEQ)=NUPCALC(JSEQ)+1
  I1UPST(JSEQ,NUPCALC(JSEQ))=ISEQ
ENDDO
DO ISEQ=1,NSEQMAX
  IX=I1SEQX(ISEQ)
  IY=I1SEQY(ISEQ)
  I2VECTOR(IX,IY)=ISEQ
  JSEQ=I1NEXT(ISEQ)
  IF( JSEQ>0 )THEN
    I2NEXTX(IX,IY)=I1SEQX(JSEQ)
    I2NEXTY(IX,IY)=I1SEQY(JSEQ)
  ELSE
    I2NEXTX(IX,IY)=JSEQ
    I2NEXTY(IX,IY)=JSEQ
  ENDIF
ENDDO
DEALLOCATE(SEQX_RAW,SEQY_RAW,NEXT_RAW,NUPCALC,NUPWORK,QUEUE,ORDER)
END SUBROUTINE READ_ROUTING_MAP_CDF
#endif
SUBROUTINE READ_MAP_BIN
USE YOS_CMF_INPUT,      ONLY: TMPNAM, LMAPEND
USE YOS_CMF_INPUT,      ONLY: WEST,EAST,NORTH,SOUTH
USE CMF_UTILS_MOD,      ONLY: INQUIRE_FID, CONV_ENDI
IMPLICIT NONE
!* local variables
INTEGER(KIND=JPIM),SAVE    :: IX,IY
!==========================================================
!*** read river map
WRITE(LOGNAM,*)'RIVMAP_INIT: nextxy binary: ',TRIM(CNEXTXY)
TMPNAM=INQUIRE_FID()
OPEN(TMPNAM,FILE=CNEXTXY,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) I2NEXTX
READ(TMPNAM,REC=2) I2NEXTY
CLOSE(TMPNAM)

IF ( LMAPEND )THEN
  CALL CONV_ENDI(I2NEXTX,NX,NY)
  CALL CONV_ENDI(I2NEXTY,NX,NY)
ENDIF

!*** calculate lat, lon
IF( WEST>=-180._JPRB .and. EAST<=360._JPRB .and. SOUTH>=-180._JPRB .and. NORTH<=180._JPRB )THEN  !! bugfix_v396a
  !$OMP PARALLEL DO
  DO IX=1,NX
    D1LON(IX)=WEST +(REAL(IX,KIND=JPRB)-0.5_JPRB)*(EAST-WEST)  /REAL(NX,KIND=JPRB)
  ENDDO
  !$OMP END PARALLEL DO
  !$OMP PARALLEL DO
  DO IY=1,NY
    D1LAT(IY)=NORTH-(REAL(IY,KIND=JPRB)-0.5_JPRB)*(NORTH-SOUTH)/REAL(NY,KIND=JPRB)
  ENDDO
  !$OMP END PARALLEL DO
ENDIF

END SUBROUTINE READ_MAP_BIN
!==========================================================
!+
!+
!+
!==========================================================
#ifdef UseCDF_CMF
SUBROUTINE READ_MAP_CDF
USE CMF_UTILS_MOD  ,ONLY: NCERROR
USE NETCDF
IMPLICIT NONE
!* local variables
INTEGER(KIND=JPIM)              :: NCID,VARID
!================================================
WRITE(LOGNAM,*)'RIVMAP_INIT: nextxy netCDF: ', TRIM(CRIVCLINC)

CALL NCERROR (NF90_OPEN(CRIVCLINC,NF90_NOWRITE,NCID),'opening '//TRIM(CRIVCLINC) )

!*** next xy
CALL NCERROR ( NF90_INQ_VARID(NCID,'nextx',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,I2NEXTX),'reading data' ) 

CALL NCERROR ( NF90_INQ_VARID(NCID,'nexty',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,I2NEXTY),'reading data' )

!*** lat, lon
CALL NCERROR ( NF90_INQ_VARID(NCID,'lat',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,D1LAT),'reading data' )

CALL NCERROR ( NF90_INQ_VARID(NCID,'lon',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,D1LON),'reading data' )

CALL NCERROR( NF90_CLOSE(NCID))

END SUBROUTINE READ_MAP_CDF
#endif
!==========================================================
!+
!+
!+
!==========================================================
SUBROUTINE CALC_REGION    !! evenly allocate pixels to mpi nodes (updated in v4.03. MPI region given from file)
USE YOS_CMF_INPUT,           ONLY: IMIS
#ifdef UseCDF_CMF
USE CMF_UTILS_MOD,           ONLY: NCERROR
USE NETCDF
#endif
IMPLICIT NONE
!* local variables
INTEGER(KIND=JPIM),ALLOCATABLE  :: REGIONGRID(:)
!
INTEGER(KIND=JPIM),SAVE         :: IX,IY
INTEGER(KIND=JPIM),SAVE         :: IREGION
INTEGER(KIND=JPIM),SAVE         :: NSEQMAX_MPI
#ifdef UseMPI_CMF
#ifdef UseCDF_CMF
INTEGER(KIND=JPIM)              :: NCID
INTEGER(KIND=JPIM)              :: VARID
#endif
#endif
!$OMP THREADPRIVATE               (IX)
!================================================
WRITE(LOGNAM,*) 'RIVMAP_INIT: region code'

!*** when MPI is not used. Treat all grid as region=1
REGIONALL=1
I2REGION(:,:)=IMIS
!$OMP PARALLEL DO
DO IY=1, NY
  DO IX=1, NX
    IF( I2NEXTX(IX,IY)/=IMIS ) THEN
      I2REGION(IX,IY)=1
    ENDIF
  ENDDO
ENDDO
!$OMP END PARALLEL DO

!*** read MPI region map
!! Use MPI: read MPI region map, allocate regions to MPI nodes
#ifdef UseMPI_CMF
  IF ( LMAPCDF ) THEN
#ifdef UseCDF_CMF
    CALL NCERROR (NF90_OPEN(CMPIREGNC,NF90_NOWRITE,NCID),'opening '//TRIM(CMPIREGNC) )
    CALL NCERROR (NF90_INQ_VARID(NCID, 'mpireg',VARID),'getting id' )
    CALL NCERROR (NF90_GET_VAR(NCID,VARID,I2REGION),'reading data' )
    CALL NCERROR (NF90_CLOSE(NCID))
#endif
  ELSE
    WRITE(LOGNAM,*)'RIVMAP_INIT: read MPI region: ',TRIM(CNEXTXY)
    TMPNAM=INQUIRE_FID()
    OPEN(TMPNAM,FILE=CMPIREG,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
    READ(TMPNAM,REC=1) I2REGION
    CLOSE(TMPNAM)
  ENDIF

  REGIONALL=1
!$OMP PARALLEL DO REDUCTION(max:REGIONALL)
  DO IY=1, NY
    DO IX=1, NX
      REGIONALL=MAX( REGIONALL, I2REGION(IX,IY) )
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
#endif


WRITE(LOGNAM,*)'RIVMAP_INIT: count number of grid in each region: '
ALLOCATE(REGIONGRID(REGIONALL))
REGIONGRID(:)=0
!! OMP reduction operation for array might not be available in some environment
DO IY=1, NY
  DO IX=1, NX
    IF( I2REGION(IX,IY)>0 ) THEN
      IREGION=I2REGION(IX,IY)
      REGIONGRID(IREGION)=REGIONGRID(IREGION)+1
    ENDIF
  ENDDO
ENDDO

NSEQMAX=0
NSEQMAX_MPI=0
DO IREGION=1, REGIONALL
  IF( IREGION==REGIONTHIS ) NSEQMAX=REGIONGRID(IREGION)
  NSEQMAX_MPI=MAX(NSEQMAX,REGIONGRID(IREGION))  !! maximum nseqmax among all MPI region
ENDDO

WRITE(LOGNAM,*) 'CALC_REGION: REGIONALL= ', REGIONALL
WRITE(LOGNAM,*) 'CALC_REGION: NSEQMAX='   , NSEQMAX
WRITE(LOGNAM,*) 'CALC_REGION: NSEQMAX='   , NSEQMAX_MPI

END SUBROUTINE CALC_REGION
!==========================================================
!+
!+
!+
!==========================================================
SUBROUTINE CALC_1D_SEQ
! OpenMP is not used, because results of this subroutine highly depents on calculation order
USE YOS_CMF_INPUT,           ONLY: IMIS
IMPLICIT NONE
!* local variables
INTEGER(KIND=JPIM)              :: IX,IY,JX,JY,ISEQ,JSEQ,ISEQ1,ISEQ2,AGAIN
INTEGER(KIND=JPIM)              :: UPNMAX

INTEGER(KIND=JPIM),ALLOCATABLE  :: NUPST(:,:), UPNOW(:,:)
!================================================
WRITE(LOGNAM,*) 'RIVMAP_INIT: convert 2D map to 1D sequence'

ALLOCATE( NUPST(NX,NY) )
ALLOCATE( UPNOW(NX,NY) )

ALLOCATE( I1SEQX(NSEQMAX) )
ALLOCATE( I1SEQY(NSEQMAX) )
ALLOCATE( I1NEXT(NSEQMAX) )
ALLOCATE( I2VECTOR(NX,NY) )
I1SEQX(:)=0
I1SEQY(:)=0
I1NEXT(:)=0
I2VECTOR(:,:)=0

! count number of upstream 
NUPST(:,:)=0
UPNOW(:,:)=0
UPNMAX=0
DO IY=1, NY
  DO IX=1, NX
    IF( I2NEXTX(IX,IY).GT.0 .and. I2REGION(IX,IY)==REGIONTHIS )THEN
      JX=I2NEXTX(IX,IY)
      JY=I2NEXTY(IX,IY)
      NUPST(JX,JY)=NUPST(JX,JY)+1
      UPNMAX=max(UPNMAX,NUPST(JX,JY))
    ENDIF
  ENDDO
ENDDO

! register upmost grid in 1d sequence
ISEQ=0
DO IY=1, NY
  DO IX=1, NX
    IF( I2NEXTX(IX,IY).GT.0 .and. I2REGION(IX,IY)==REGIONTHIS )THEN
      IF( NUPST(IX,IY)==UPNOW(IX,IY) )THEN
        ISEQ=ISEQ+1
        I1SEQX(ISEQ)=IX
        I1SEQY(ISEQ)=IY
        I2VECTOR(IX,IY)=ISEQ
      ENDIF
    ENDIF
  ENDDO
ENDDO
ISEQ1=1
ISEQ2=ISEQ

AGAIN=1
DO WHILE( AGAIN==1 )
  AGAIN=0
  JSEQ=ISEQ2
  DO ISEQ=ISEQ1, ISEQ2
    IX=I1SEQX(ISEQ)
    IY=I1SEQY(ISEQ)
    JX=I2NEXTX(IX,IY)
    JY=I2NEXTY(IX,IY)
    UPNOW(JX,JY)=UPNOW(JX,JY)+1
    IF( UPNOW(JX,JY)==NUPST(JX,JY) .and. I2NEXTX(JX,JY)>0 )THEN !! if all upstream calculated, register to 1D sequence
      JSEQ=JSEQ+1
      I1SEQX(JSEQ)=JX
      I1SEQY(JSEQ)=JY
      I2VECTOR(JX,JY)=JSEQ
      AGAIN=1
    ENDIF
  ENDDO
  ISEQ1=ISEQ2+1
  ISEQ2=JSEQ
ENDDO
NSEQRIV=JSEQ    !! END OF RIVER-LINK GRID

ISEQ=NSEQRIV
DO IY=1, NY
  DO IX=1, NX
    IF( I2NEXTX(IX,IY).LT.0 .AND. I2NEXTX(IX,IY).NE.IMIS .AND. I2REGION(IX,IY)==REGIONTHIS )THEN
      ISEQ=ISEQ+1
      I1SEQX(ISEQ)=IX
      I1SEQY(ISEQ)=IY
      I2VECTOR(IX,IY)=ISEQ
    ENDIF
  ENDDO
ENDDO
NSEQALL=ISEQ    !! END OF RIVER-MOUTH GRID

DO ISEQ=1, NSEQALL
  IX=I1SEQX(ISEQ)
  IY=I1SEQY(ISEQ)
  IF( I2NEXTX(IX,IY)>0 )THEN
    JX=I2NEXTX(IX,IY)
    JY=I2NEXTY(IX,IY)
    I1NEXT(ISEQ)=I2VECTOR(JX,JY)
  ELSE
    I1NEXT(ISEQ)=I2NEXTX(IX,IY)
  ENDIF
ENDDO

DEALLOCATE(NUPST,UPNOW)

WRITE(LOGNAM,*) 'CALC_1DSEQ: NSEQRIV='   , NSEQRIV
WRITE(LOGNAM,*) 'CALC_1DSEQ: NSEQALL='   , NSEQALL

!====
!!IF( LSPAMAT )THEN
  WRITE(LOGNAM,*) 'RIVMAP_INIT: Upstream Matrix size', UPNMAX
  ALLOCATE(I1UPST(NSEQMAX,UPNMAX),I1UPN(NSEQMAX))
  I1UPST(:,:)=-9999
  I1UPN(:)=0
  DO ISEQ=1, NSEQRIV
    JSEQ=I1NEXT(ISEQ)
    I1UPN(JSEQ)=I1UPN(JSEQ)+1
    I1UPST(JSEQ,I1UPN(JSEQ))=ISEQ
  ENDDO
!!ENDIF

END SUBROUTINE CALC_1D_SEQ
!==========================================================
!+
!+
!+
!==========================================================
#ifdef UseCDF_CMF
SUBROUTINE READ_ROUTING_BIF_CDF
USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
USE YOS_CMF_MAP, ONLY: PTH_UPST,PTH_DOWN,PTH_DST,PTH_ELV,PTH_WTH,PTH_MAN, ROUTING_OLD_TO_NEW
USE CMF_UTILS_MOD, ONLY: NCERROR
USE NETCDF
IMPLICIT NONE
INTEGER(KIND=JPIM) :: NCID,VARID,DIMID,STATUS,DIMIDS1(1),DIMIDS2(2)
INTEGER(KIND=JPIM) :: IPTH,ILEV,ISEQ,JSEQ,ONMAX,INMAX,LEN1,LEN2,PATH_DIMID,LEV_DIMID
INTEGER(KIND=JPIM),ALLOCATABLE :: OCOUNT(:),ICOUNT(:)
REAL(KIND=JPRB),ALLOCATABLE :: RTEMP(:,:)

CALL NCERROR(NF90_OPEN(TRIM(CROUTINGNC),NF90_NOWRITE,NCID), &
             'opening '//TRIM(CROUTINGNC))
STATUS=NF90_INQ_DIMID(NCID,'npthout',DIMID)
IF( STATUS==NF90_NOERR )THEN
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=NPTHOUT),'reading npthout dimension')
ELSE
  CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_upst',VARID),'getting bifurcation_upst id')
  CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS1),'reading bifurcation_upst dimensions')
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS1(1),LEN=NPTHOUT),'reading bifurcation count')
ENDIF
STATUS=NF90_INQ_DIMID(NCID,'npthlev',DIMID)
IF( STATUS==NF90_NOERR )THEN
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMID,LEN=NPTHLEV),'reading npthlev dimension')
ELSE
  CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_manning',VARID),'getting bifurcation_manning id')
  CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS1),'reading bifurcation_manning dimensions')
  CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS1(1),LEN=NPTHLEV),'reading bifurcation level count')
ENDIF
IF( NPTHOUT<=0 .OR. NPTHLEV<=0 )THEN
  WRITE(LOGNAM,*) 'Invalid bifurcation dimensions: ',NPTHOUT,NPTHLEV
  STOP 10
ENDIF

ALLOCATE(PTH_UPST(NPTHOUT),PTH_DOWN(NPTHOUT),PTH_DST(NPTHOUT))
ALLOCATE(PTH_ELV(NPTHOUT,NPTHLEV),PTH_WTH(NPTHOUT,NPTHLEV),PTH_MAN(NPTHLEV))

CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_upst',VARID),'getting bifurcation_upst id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS1),'reading bifurcation_upst dimensions')
PATH_DIMID=DIMIDS1(1)
CALL NCERROR(NF90_GET_VAR(NCID,VARID,PTH_UPST),'reading bifurcation_upst')
CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_down',VARID),'getting bifurcation_down id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,PTH_DOWN),'reading bifurcation_down')
CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_distance',VARID),'getting bifurcation_distance id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,PTH_DST),'reading bifurcation_distance')
CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_manning',VARID),'getting bifurcation_manning id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS1),'reading bifurcation_manning dimensions')
LEV_DIMID=DIMIDS1(1)

CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_elevation',VARID),'getting bifurcation_elevation id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS2),'reading bifurcation_elevation dimensions')
CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(1),LEN=LEN1),'reading bifurcation_elevation dimension')
CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(2),LEN=LEN2),'reading bifurcation_elevation dimension')
IF( DIMIDS2(1)==PATH_DIMID .AND. DIMIDS2(2)==LEV_DIMID )THEN
  ALLOCATE(RTEMP(NPTHOUT,NPTHLEV))
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,RTEMP),'reading bifurcation_elevation')
  PTH_ELV=RTEMP
ELSEIF( DIMIDS2(1)==LEV_DIMID .AND. DIMIDS2(2)==PATH_DIMID )THEN
  ALLOCATE(RTEMP(NPTHLEV,NPTHOUT))
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,RTEMP),'reading bifurcation_elevation')
  PTH_ELV=TRANSPOSE(RTEMP)
ELSE
  WRITE(LOGNAM,*) 'Invalid bifurcation_elevation dimensions: ',LEN1,LEN2,NPTHOUT,NPTHLEV
  STOP 10
ENDIF
DEALLOCATE(RTEMP)

CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_width',VARID),'getting bifurcation_width id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS2),'reading bifurcation_width dimensions')
CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(1),LEN=LEN1),'reading bifurcation_width dimension')
CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(2),LEN=LEN2),'reading bifurcation_width dimension')
IF( DIMIDS2(1)==PATH_DIMID .AND. DIMIDS2(2)==LEV_DIMID )THEN
  ALLOCATE(RTEMP(NPTHOUT,NPTHLEV))
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,RTEMP),'reading bifurcation_width')
  PTH_WTH=RTEMP
ELSEIF( DIMIDS2(1)==LEV_DIMID .AND. DIMIDS2(2)==PATH_DIMID )THEN
  ALLOCATE(RTEMP(NPTHLEV,NPTHOUT))
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,RTEMP),'reading bifurcation_width')
  PTH_WTH=TRANSPOSE(RTEMP)
ELSE
  WRITE(LOGNAM,*) 'Invalid bifurcation_width dimensions: ',LEN1,LEN2,NPTHOUT,NPTHLEV
  STOP 10
ENDIF
DEALLOCATE(RTEMP)

CALL NCERROR(NF90_INQ_VARID(NCID,'bifurcation_manning',VARID),'getting bifurcation_manning id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS1),'reading bifurcation_manning dimensions')
LEV_DIMID=DIMIDS1(1)
CALL NCERROR(NF90_GET_VAR(NCID,VARID,PTH_MAN),'reading bifurcation_manning')
CALL NCERROR(NF90_CLOSE(NCID))

IF( ANY(PTH_UPST<1) .OR. ANY(PTH_UPST>NSEQMAX) .OR. &
    ANY(PTH_DOWN<1) .OR. ANY(PTH_DOWN>NSEQMAX) .OR. &
    ANY(PTH_UPST==PTH_DOWN) )THEN
  WRITE(LOGNAM,*) 'Invalid bifurcation sequence index in routing netCDF'
  STOP 10
ENDIF
IF( ALLOCATED(ROUTING_OLD_TO_NEW) )THEN
  DO IPTH=1,NPTHOUT
    PTH_UPST(IPTH)=ROUTING_OLD_TO_NEW(PTH_UPST(IPTH))
    PTH_DOWN(IPTH)=ROUTING_OLD_TO_NEW(PTH_DOWN(IPTH))
  ENDDO
ENDIF
IF( ANY(.NOT. IEEE_IS_FINITE(PTH_DST)) .OR. ANY(.NOT. IEEE_IS_FINITE(PTH_ELV)) .OR. &
    ANY(.NOT. IEEE_IS_FINITE(PTH_WTH)) .OR. ANY(.NOT. IEEE_IS_FINITE(PTH_MAN)) )THEN
  WRITE(LOGNAM,*) 'Non-finite bifurcation parameter in routing netCDF'
  STOP 10
ENDIF
IF( ANY(PTH_DST<=0._JPRB) .OR. ANY(PTH_WTH<0._JPRB) )THEN
  WRITE(LOGNAM,*) 'Invalid bifurcation distance/width in routing netCDF'
  STOP 10
ENDIF
DO ILEV=1,NPTHLEV
  IF( ANY(PTH_WTH(:,ILEV)>0._JPRB) .AND. PTH_MAN(ILEV)<=0._JPRB )THEN
    WRITE(LOGNAM,*) 'Invalid bifurcation Manning coefficient at level ',ILEV
    STOP 10
  ENDIF
ENDDO

ALLOCATE(OCOUNT(NSEQMAX),ICOUNT(NSEQMAX))
OCOUNT(:)=0
ICOUNT(:)=0
DO IPTH=1,NPTHOUT
  OCOUNT(PTH_UPST(IPTH))=OCOUNT(PTH_UPST(IPTH))+1
  ICOUNT(PTH_DOWN(IPTH))=ICOUNT(PTH_DOWN(IPTH))+1
ENDDO
ONMAX=MAXVAL(OCOUNT)
INMAX=MAXVAL(ICOUNT)
ALLOCATE(I1P_OUT(NSEQMAX,ONMAX),I1P_INF(NSEQMAX,INMAX))
ALLOCATE(I1P_OUTN(NSEQMAX),I1P_INFN(NSEQMAX))
I1P_OUT(:,:)=0
I1P_INF(:,:)=0
I1P_OUTN(:)=0
I1P_INFN(:)=0
DO IPTH=1,NPTHOUT
  ISEQ=PTH_UPST(IPTH)
  JSEQ=PTH_DOWN(IPTH)
  I1P_OUTN(ISEQ)=I1P_OUTN(ISEQ)+1
  I1P_OUT(ISEQ,I1P_OUTN(ISEQ))=IPTH
  I1P_INFN(JSEQ)=I1P_INFN(JSEQ)+1
  I1P_INF(JSEQ,I1P_INFN(JSEQ))=IPTH
ENDDO
DEALLOCATE(OCOUNT,ICOUNT)
END SUBROUTINE READ_ROUTING_BIF_CDF
#endif
SUBROUTINE READ_BIFPARAM    !! evenly allocate pixels to mpi nodes (not used in vcurrent version)
USE YOS_CMF_INPUT,      ONLY: PMANRIV, PMANFLD
USE YOS_CMF_MAP,        ONLY: NPTHOUT, NPTHLEV, PTH_UPST, PTH_DOWN,&
                            & PTH_DST, PTH_ELV, PTH_WTH,  PTH_MAN, NSEQMAX
USE CMF_UTILS_MOD,      ONLY: INQUIRE_FID
IMPLICIT NONE
!* local variables
INTEGER(KIND=JPIM)         :: IX,IY, JX,JY, ISEQ, JSEQ
INTEGER(KIND=JPIM)         :: IPTH,  ILEV,  NPTHOUT1
REAL(KIND=JPRB)            :: PELV,  PWTH,  PDPH
INTEGER(KIND=JPIM)         :: ONMAX,  INMAX
INTEGER(KIND=JPIM)         :: OCOUNT(NSEQMAX),  ICOUNT(NSEQMAX)
!================================================
WRITE(LOGNAM,*)"RIVMAP_INIT: Bifuraction channel:", TRIM(CPTHOUT)

TMPNAM=INQUIRE_FID()
OPEN(TMPNAM,FILE=CPTHOUT,FORM='FORMATTED')
READ(TMPNAM,*) NPTHOUT,NPTHLEV

WRITE(LOGNAM,*) "Bifurcation channel dimantion", NPTHOUT, NPTHLEV

ALLOCATE( PTH_UPST(NPTHOUT) )
ALLOCATE( PTH_DOWN(NPTHOUT) )
ALLOCATE( PTH_DST(NPTHOUT)  )
ALLOCATE( PTH_ELV(NPTHOUT,NPTHLEV) )
ALLOCATE( PTH_WTH(NPTHOUT,NPTHLEV) )
ALLOCATE( PTH_MAN(NPTHLEV)  )

OCOUNT(:)=0
ICOUNT(:)=0

NPTHOUT1=0
DO IPTH=1, NPTHOUT
  READ(TMPNAM,*) IX, IY, JX, JY, PTH_DST(IPTH), PELV, PDPH, (PTH_WTH(IPTH,ILEV),ILEV=1,NPTHLEV)
  PTH_UPST(IPTH)=I2VECTOR(IX,IY)
  PTH_DOWN(IPTH)=I2VECTOR(JX,JY)
  IF (PTH_UPST(IPTH) > 0 .AND. PTH_DOWN(IPTH) > 0) THEN  ! both upst and down grids are within domain
    NPTHOUT1=NPTHOUT1+1
    ISEQ=PTH_UPST(IPTH)
    JSEQ=PTH_DOWN(IPTH)
    OCOUNT(ISEQ)=OCOUNT(ISEQ)+1
    ICOUNT(JSEQ)=ICOUNT(JSEQ)+1
  ENDIF
  DO ILEV=1, NPTHLEV
    IF( ILEV==1 )THEN            !!ILEV=1: water channel bifurcation. consider bifurcation channel depth
      PWTH=PTH_WTH(IPTH,ILEV)
      IF( PWTH>0 )THEN
        PTH_ELV(IPTH,ILEV)=PELV - PDPH
      ELSE
        PTH_ELV(IPTH,ILEV)=1.E20
      ENDIF
    ELSE
      PWTH=PTH_WTH(IPTH,ILEV)
      IF( PWTH>0 )THEN
        PTH_ELV(IPTH,ILEV)=PELV + ILEV - 2.0    !! ILEV=2: bank top level 
      ELSE
        PTH_ELV(IPTH,ILEV)=1.E20
      ENDIF
    ENDIF
  ENDDO
ENDDO
CLOSE(TMPNAM)

DO ILEV=1, NPTHLEV
  IF( ILEV==1 )THEN
    PTH_MAN(ILEV)=PMANRIV
  ELSE
    PTH_MAN(ILEV)=PMANFLD
  ENDIF
ENDDO

IF (NPTHOUT /= NPTHOUT1) THEN
  WRITE(LOGNAM,*)"Bifuraction channel outside of domain. Only valid:", NPTHOUT1
ENDIF

!=====
!!IF( LSPAMAT )THEN
  ONMAX=0
  INMAX=0
  DO ISEQ=1, NSEQMAX
    ONMAX=max(ONMAX,OCOUNT(ISEQ))
    INMAX=max(INMAX,ICOUNT(ISEQ))
  ENDDO
  WRITE(LOGNAM,*) "Max # of Bifuraction channel in each grid (Out, Inf):", ONMAX, INMAX
  
  ALLOCATE(I1P_OUT(NSEQMAX,ONMAX))
  ALLOCATE(I1P_INF(NSEQMAX,INMAX))
  ALLOCATE(I1P_OUTN(NSEQMAX))
  ALLOCATE(I1P_INFN(NSEQMAX))
  I1P_OUT(:,:)=0
  I1P_INF(:,:)=0
  I1P_OUTN(:)=0
  I1P_INFN(:)=0

  DO IPTH=1, NPTHOUT
    IF (PTH_UPST(IPTH) > 0 .AND. PTH_DOWN(IPTH) > 0) THEN  ! both upst and down grids are within domain
      ISEQ=PTH_UPST(IPTH)
      JSEQ=PTH_DOWN(IPTH)
  
      I1P_OUTN(ISEQ)=I1P_OUTN(ISEQ)+1
      I1P_OUT(ISEQ,I1P_OUTN(ISEQ))=IPTH
  
      I1P_INFN(JSEQ)=I1P_INFN(JSEQ)+1
      I1P_INF(JSEQ,I1P_INFN(JSEQ))=IPTH
    ENDIF
  ENDDO
!!ENDIF

END SUBROUTINE READ_BIFPARAM
!==========================================================


END SUBROUTINE CMF_RIVMAP_INIT
!####################################################################





!####################################################################
SUBROUTINE CMF_TOPO_INIT
! read & set topography map 
! -- call from CMF_DRV_INIT
USE YOS_CMF_INPUT,  ONLY: TMPNAM,   NX,NY,NLFP, LMAPEND,  &
                        & LFPLAIN,  LMEANSL,  LGDWDLY,  LSLPMIX, LSLOPEMOUTH
USE YOS_CMF_MAP,    ONLY: D2NXTDST, D2GRAREA, D2ELEVTN, D2RIVLEN, &
                        & D2RIVWTH, D2RIVHGT, D2FLDHGT, D2RIVELV, &
                        & D2FLDGRD, D2RIVMAN, D2RIVSTOMAX, D2FLDSTOMAX,  &
                        & DFRCINC,  NSEQMAX,  D2MEANSL, D2DWNELV, &
                        & D2GDWDLY, I2MASK, R2GRDARE, ROUTING_OLD_TO_NEW
IMPLICIT NONE
!================================================
WRITE(LOGNAM,*) ""
WRITE(LOGNAM,*) "!---------------------!"

WRITE(LOGNAM,*) 'CMF::TOPO_INIT: topography map initialization'

! *** 1. ALLOCATE ARRAYS
ALLOCATE( D2GRAREA(NSEQMAX,1) )
ALLOCATE( D2ELEVTN(NSEQMAX,1) )
ALLOCATE( D2NXTDST(NSEQMAX,1) )
ALLOCATE( D2RIVLEN(NSEQMAX,1) )
ALLOCATE( D2RIVWTH(NSEQMAX,1) )
ALLOCATE( D2RIVHGT(NSEQMAX,1) )
ALLOCATE( D2FLDHGT(NSEQMAX,1,NLFP) )
ALLOCATE( D2RIVMAN(NSEQMAX,1) )
ALLOCATE( D2MEANSL(NSEQMAX,1) )
ALLOCATE( D2DWNELV(NSEQMAX,1) )
ALLOCATE( D2GDWDLY(NSEQMAX,1) )
ALLOCATE( I2MASK(NSEQMAX,1)   )
ALLOCATE( R2GRDARE(NX,NY)     )

D2GRAREA(:,:)  =0._JPRB
D2ELEVTN(:,:)  =0._JPRB
D2NXTDST(:,:)  =0._JPRB
D2RIVLEN(:,:)  =0._JPRB
D2RIVWTH(:,:)  =0._JPRB
D2RIVHGT(:,:)  =0._JPRB
D2FLDHGT(:,:,:)=0._JPRB
D2RIVMAN(:,:)  =0._JPRB
D2MEANSL(:,:)  =0._JPRB
D2DWNELV(:,:)  =0._JPRB
D2GDWDLY(:,:)  =0._JPRB
I2MASK(:,:)    =0._JPIM     !! mask for calculation (IFS slopemix: Kinemacti Wave for Mask=1; Reservoir: dam=2, dam upstream=1)
R2GRDARE(:,:)  =0._JPRB

!============================
! *** 2. Read topo map
WRITE(LOGNAM,*) 'CMF::TOPO_INIT: read topography maps'
IF( CROUTINGNC/="NONE" )THEN
  CALL READ_ROUTING_TOPO_CDF
ELSEIF ( .not. LMAPCDF ) THEN
  CALL READ_TOPO_BIN
ELSE
  CALL READ_TOPO_CDF
ENDIF

IF ( CROUTINGNC=="NONE" ) I2MASK(:,:)=0_JPIM
IF ( LSLPMIX .AND. CROUTINGNC=="NONE" ) THEN
  CALL SET_SLOPEMIX
ENDIF

!============================
! *** 3a. Calc Channel Parameters
WRITE(LOGNAM,*) 'TOPO_INIT: calc river channel parameters'

ALLOCATE(D2RIVSTOMAX(NSEQMAX,1))
ALLOCATE(D2RIVELV(NSEQMAX,1))

IF ( LFPLAIN ) THEN
  D2RIVSTOMAX(:,:) = D2RIVLEN(:,:) * D2RIVWTH(:,:) * D2RIVHGT(:,:)
ELSE
  WRITE(LOGNAM,*) 'TOPO_INIT: no floodplain (rivstomax=1.D18)'
  D2RIVSTOMAX(:,:) = 1.E18
ENDIF
D2RIVELV(:,:) = D2ELEVTN(:,:) - D2RIVHGT(:,:)

!*** 3b. Calc Channel Parameters
WRITE(LOGNAM,*) 'TOPO_INIT: calc floodplain parameters'

ALLOCATE(D2FLDSTOMAX(NSEQMAX,1,NLFP))
ALLOCATE(D2FLDGRD(NSEQMAX,1,NLFP))
CALL SET_FLDSTG

!*** 3c. Calc downstream boundary
WRITE(LOGNAM,*) 'TOPO_INIT: calc downstream boundary elevation'
D2DWNELV(:,:)=D2ELEVTN(:,:)
IF( LMEANSL ) THEN
  D2DWNELV(:,:)=D2ELEVTN(:,:)+D2MEANSL(:,:)
ENDIF

CONTAINS
!==========================================================
!+ READ_TOPO_BIN
!+ READ_TOPO_CDF
!+ SET_FLDSTG
!+ SET_SLOPEMIX
!==========================================================
#ifdef UseCDF_CMF
SUBROUTINE READ_ROUTING_TOPO_CDF
USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
USE YOS_CMF_INPUT, ONLY: WEST,EAST,NORTH,SOUTH
USE YOS_CMF_MAP, ONLY: D2ELEVSLOPE
USE CMF_UTILS_MOD, ONLY: NCERROR
USE NETCDF
IMPLICIT NONE
INTEGER(KIND=JPIM) :: NCID,VARID,STATUS,ILEV,IY,DIMIDS2(2),LEN1,LEN2,ISEQ,SEQDIM(1)
INTEGER(KIND=JPIM),ALLOCATABLE :: ITMP(:)
REAL(KIND=JPRB),ALLOCATABLE :: RTEMP(:,:),RIVELV(:),STO_IN(:),STO_EXPECT(:),R1(:),R3(:,:)
REAL(KIND=JPRB) :: DLON,DLAT,LATN,LATS,ROWEAREA
LOGICAL :: HAVE_PERM
REAL(KIND=JPRB),PARAMETER :: REARTH=6371220._JPRB
REAL(KIND=JPRB),PARAMETER :: DEG2RAD=1.7453292519943296E-2_JPRB

CALL NCERROR(NF90_OPEN(TRIM(CROUTINGNC),NF90_NOWRITE,NCID), &
             'opening '//TRIM(CROUTINGNC))
CALL NCERROR(NF90_INQ_VARID(NCID,'seq_x',VARID),'getting seq_x id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=SEQDIM),'reading sequence dimension')
CALL NCERROR(NF90_INQ_VARID(NCID,'topo_area',VARID),'getting topo_area id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2GRAREA(:,1)),'reading topo_area')

STATUS=NF90_INQ_VARID(NCID,'topo_distance',VARID)
IF( STATUS/=NF90_NOERR ) STATUS=NF90_INQ_VARID(NCID,'topo_nxtdst',VARID)
IF( STATUS/=NF90_NOERR )THEN
  WRITE(LOGNAM,*) 'topo_distance/topo_nxtdst not present in routing netCDF'
  WRITE(LOGNAM,*) 'Cannot derive downstream distance from topo_rivlen safely.'
  STOP 10
ENDIF
CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2NXTDST(:,1)),'reading topo_distance')

CALL NCERROR(NF90_INQ_VARID(NCID,'topo_rivlen',VARID),'getting topo_rivlen id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2RIVLEN(:,1)),'reading topo_rivlen')
CALL NCERROR(NF90_INQ_VARID(NCID,'topo_rivwth',VARID),'getting topo_rivwth id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2RIVWTH(:,1)),'reading topo_rivwth')
CALL NCERROR(NF90_INQ_VARID(NCID,'topo_rivhgt',VARID),'getting topo_rivhgt id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2RIVHGT(:,1)),'reading topo_rivhgt')
CALL NCERROR(NF90_INQ_VARID(NCID,'topo_rivman',VARID),'getting topo_rivman id')
CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2RIVMAN(:,1)),'reading topo_rivman')

STATUS=NF90_INQ_VARID(NCID,'topo_rivelv',VARID)
IF( STATUS==NF90_NOERR )THEN
  ALLOCATE(RIVELV(NSEQMAX))
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,RIVELV),'reading topo_rivelv')
  D2ELEVTN(:,1)=RIVELV(:)+D2RIVHGT(:,1)
  DEALLOCATE(RIVELV)
ELSE
  STATUS=NF90_INQ_VARID(NCID,'topo_elevation',VARID)
  IF( STATUS/=NF90_NOERR )THEN
    WRITE(LOGNAM,*) 'topo_elevation/topo_rivelv not present in routing netCDF'
    WRITE(LOGNAM,*) 'Need bank elevation or river-bed elevation plus topo_rivhgt.'
    STOP 10
  ENDIF
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2ELEVTN(:,1)),'reading topo_elevation')
ENDIF

CALL NCERROR(NF90_INQ_VARID(NCID,'topo_fldhgt',VARID),'getting topo_fldhgt id')
CALL NCERROR(NF90_INQUIRE_VARIABLE(NCID,VARID,DIMIDS=DIMIDS2),'reading topo_fldhgt dimensions')
CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(1),LEN=LEN1),'reading topo_fldhgt dimension')
CALL NCERROR(NF90_INQUIRE_DIMENSION(NCID,DIMIDS2(2),LEN=LEN2),'reading topo_fldhgt dimension')
IF( DIMIDS2(1)==SEQDIM(1) .AND. LEN1==NSEQMAX .AND. LEN2==NLFP )THEN
  ALLOCATE(RTEMP(NSEQMAX,NLFP))
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,RTEMP),'reading topo_fldhgt')
  DO ILEV=1,NLFP
    D2FLDHGT(:,1,ILEV)=RTEMP(:,ILEV)
  ENDDO
  DEALLOCATE(RTEMP)
ELSEIF( DIMIDS2(2)==SEQDIM(1) .AND. LEN1==NLFP .AND. LEN2==NSEQMAX )THEN
  ALLOCATE(RTEMP(NLFP,NSEQMAX))
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,RTEMP),'reading topo_fldhgt')
  DO ILEV=1,NLFP
    D2FLDHGT(:,1,ILEV)=RTEMP(ILEV,:)
  ENDDO
  DEALLOCATE(RTEMP)
ELSE
  WRITE(LOGNAM,*) 'topo_fldhgt dimensions do not match sequence count and NLFP: ',LEN1,LEN2,NSEQMAX,NLFP
  STOP 10
ENDIF

IF( LSLOPEMOUTH )THEN
  ALLOCATE(D2ELEVSLOPE(NSEQMAX,1))
  STATUS=NF90_INQ_VARID(NCID,'topo_elevslope',VARID)
  IF( STATUS/=NF90_NOERR ) STATUS=NF90_INQ_VARID(NCID,'elevslope',VARID)
  IF( STATUS/=NF90_NOERR )THEN
    WRITE(LOGNAM,*) 'topo_elevslope not present in routing netCDF'
    STOP 10
  ENDIF
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2ELEVSLOPE(:,1)),'reading topo_elevslope')
  IF( ANY(.NOT. IEEE_IS_FINITE(D2ELEVSLOPE(:,1))) .OR. ANY(D2ELEVSLOPE(:,1)<=0._JPRB) )THEN
    WRITE(LOGNAM,*) 'Invalid topo_elevslope in routing netCDF'
    STOP 10
  ENDIF
ENDIF
IF( LSLPMIX )THEN
  STATUS=NF90_INQ_VARID(NCID,'topo_mask_slope',VARID)
  IF( STATUS/=NF90_NOERR ) STATUS=NF90_INQ_VARID(NCID,'mask_slope',VARID)
  IF( STATUS/=NF90_NOERR )THEN
    WRITE(LOGNAM,*) 'topo_mask_slope not present in routing netCDF'
    STOP 10
  ENDIF
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,I2MASK(:,1)),'reading topo_mask_slope')
  IF( ANY(I2MASK(:,1)<0) .OR. ANY(I2MASK(:,1)>1) )THEN
    WRITE(LOGNAM,*) 'Invalid topo_mask_slope in routing netCDF'
    STOP 10
  ENDIF
ENDIF
IF( LGDWDLY )THEN
  STATUS=NF90_INQ_VARID(NCID,'topo_gdwdly',VARID)
  IF( STATUS/=NF90_NOERR ) STATUS=NF90_INQ_VARID(NCID,'gdwdly',VARID)
  IF( STATUS/=NF90_NOERR )THEN
    WRITE(LOGNAM,*) 'topo_gdwdly not present in routing netCDF'
    STOP 10
  ENDIF
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2GDWDLY(:,1)),'reading topo_gdwdly')
  IF( ANY(.NOT. IEEE_IS_FINITE(D2GDWDLY(:,1))) .OR. ANY(D2GDWDLY(:,1)<0._JPRB) )THEN
    WRITE(LOGNAM,*) 'Invalid topo_gdwdly in routing netCDF'
    STOP 10
  ENDIF
ENDIF
IF( LMEANSL )THEN
  STATUS=NF90_INQ_VARID(NCID,'topo_meansl',VARID)
  IF( STATUS/=NF90_NOERR ) STATUS=NF90_INQ_VARID(NCID,'meansl',VARID)
  IF( STATUS/=NF90_NOERR )THEN
    WRITE(LOGNAM,*) 'topo_meansl not present in routing netCDF'
    STOP 10
  ENDIF
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,D2MEANSL(:,1)),'reading topo_meansl')
  IF( ANY(.NOT. IEEE_IS_FINITE(D2MEANSL(:,1))) )THEN
    WRITE(LOGNAM,*) 'Invalid topo_meansl in routing netCDF'
    STOP 10
  ENDIF
ENDIF

HAVE_PERM=ALLOCATED(ROUTING_OLD_TO_NEW)
IF( HAVE_PERM )THEN
  ALLOCATE(R1(NSEQMAX),R3(NSEQMAX,NLFP))
  R1(:)=D2GRAREA(:,1); DO ISEQ=1,NSEQMAX; D2GRAREA(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  R1(:)=D2ELEVTN(:,1); DO ISEQ=1,NSEQMAX; D2ELEVTN(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  R1(:)=D2NXTDST(:,1); DO ISEQ=1,NSEQMAX; D2NXTDST(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  R1(:)=D2RIVLEN(:,1); DO ISEQ=1,NSEQMAX; D2RIVLEN(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  R1(:)=D2RIVWTH(:,1); DO ISEQ=1,NSEQMAX; D2RIVWTH(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  R1(:)=D2RIVHGT(:,1); DO ISEQ=1,NSEQMAX; D2RIVHGT(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  R1(:)=D2RIVMAN(:,1); DO ISEQ=1,NSEQMAX; D2RIVMAN(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  DO ILEV=1,NLFP
    R3(:,ILEV)=D2FLDHGT(:,1,ILEV)
  ENDDO
  DO ISEQ=1,NSEQMAX
    DO ILEV=1,NLFP
      D2FLDHGT(ROUTING_OLD_TO_NEW(ISEQ),1,ILEV)=R3(ISEQ,ILEV)
    ENDDO
  ENDDO
  IF( LMEANSL )THEN
    R1(:)=D2MEANSL(:,1); DO ISEQ=1,NSEQMAX; D2MEANSL(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  ENDIF
  IF( LGDWDLY )THEN
    R1(:)=D2GDWDLY(:,1); DO ISEQ=1,NSEQMAX; D2GDWDLY(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  ENDIF
  IF( LSLOPEMOUTH )THEN
    R1(:)=D2ELEVSLOPE(:,1); DO ISEQ=1,NSEQMAX; D2ELEVSLOPE(ROUTING_OLD_TO_NEW(ISEQ),1)=R1(ISEQ); ENDDO
  ENDIF
  IF( LSLPMIX )THEN
    ALLOCATE(ITMP(NSEQMAX))
    ITMP(:)=I2MASK(:,1)
    DO ISEQ=1,NSEQMAX
      I2MASK(ROUTING_OLD_TO_NEW(ISEQ),1)=ITMP(ISEQ)
    ENDDO
    DEALLOCATE(ITMP)
  ENDIF
  DEALLOCATE(R1,R3)
ENDIF

IF( ANY(.NOT. IEEE_IS_FINITE(D2GRAREA(:,1))) .OR. ANY(.NOT. IEEE_IS_FINITE(D2ELEVTN(:,1))) .OR. &
    ANY(.NOT. IEEE_IS_FINITE(D2NXTDST(:,1))) .OR. ANY(.NOT. IEEE_IS_FINITE(D2RIVLEN(:,1))) .OR. &
    ANY(.NOT. IEEE_IS_FINITE(D2RIVWTH(:,1))) .OR. ANY(.NOT. IEEE_IS_FINITE(D2RIVHGT(:,1))) .OR. &
    ANY(.NOT. IEEE_IS_FINITE(D2RIVMAN(:,1))) .OR. ANY(.NOT. IEEE_IS_FINITE(D2FLDHGT(:,1,:))) )THEN
  WRITE(LOGNAM,*) 'Non-finite routing topography parameter in ',TRIM(CROUTINGNC)
  STOP 10
ENDIF
IF( ANY(D2GRAREA(:,1)<=0._JPRB) .OR. ANY(D2NXTDST(:,1)<=0._JPRB) .OR. &
    ANY(D2RIVLEN(:,1)<=0._JPRB) .OR. ANY(D2RIVWTH(:,1)<=0._JPRB) .OR. &
    ANY(D2RIVHGT(:,1)<=0._JPRB) .OR. ANY(D2RIVMAN(:,1)<=0._JPRB) )THEN
  WRITE(LOGNAM,*) 'Non-positive routing topography parameter in ',TRIM(CROUTINGNC)
  STOP 10
ENDIF
IF( ANY(D2FLDHGT(:,1,1)<0._JPRB) )THEN
  WRITE(LOGNAM,*) 'Negative floodplain height in routing netCDF'
  STOP 10
ENDIF
DO ILEV=2,NLFP
  IF( ANY(D2FLDHGT(:,1,ILEV)<D2FLDHGT(:,1,ILEV-1)) )THEN
    WRITE(LOGNAM,*) 'Floodplain height profile is not monotonic at level ',ILEV
    STOP 10
  ENDIF
ENDDO

STATUS=NF90_INQ_VARID(NCID,'topo_rivstomax',VARID)
IF( STATUS==NF90_NOERR )THEN
  ALLOCATE(STO_IN(NSEQMAX),STO_EXPECT(NSEQMAX))
  CALL NCERROR(NF90_GET_VAR(NCID,VARID,STO_IN),'reading topo_rivstomax')
  IF( HAVE_PERM )THEN
    ALLOCATE(R1(NSEQMAX))
    R1(:)=STO_IN(:)
    DO ISEQ=1,NSEQMAX
      STO_IN(ROUTING_OLD_TO_NEW(ISEQ))=R1(ISEQ)
    ENDDO
    DEALLOCATE(R1)
  ENDIF
  STO_EXPECT(:)=D2RIVLEN(:,1)*D2RIVWTH(:,1)*D2RIVHGT(:,1)
  IF( ANY(.NOT. IEEE_IS_FINITE(STO_IN)) .OR. &
      ANY(ABS(STO_IN-STO_EXPECT)>MAX(1.0E-6_JPRB,ABS(STO_EXPECT)*1.0E-6_JPRB)) )THEN
    WRITE(LOGNAM,*) 'topo_rivstomax is inconsistent with CaMa river geometry'
    STOP 10
  ENDIF
  DEALLOCATE(STO_IN,STO_EXPECT)
ENDIF

CALL NCERROR(NF90_CLOSE(NCID))

DLON=(EAST-WEST)/REAL(NX,KIND=JPRB)*DEG2RAD
DLAT=(NORTH-SOUTH)/REAL(NY,KIND=JPRB)
DO IY=1,NY
  LATN=(NORTH-REAL(IY-1,KIND=JPRB)*DLAT)*DEG2RAD
  LATS=(NORTH-REAL(IY,  KIND=JPRB)*DLAT)*DEG2RAD
  ROWEAREA=REARTH*REARTH*DLON*(SIN(LATN)-SIN(LATS))
  R2GRDARE(:,IY)=ROWEAREA
ENDDO
END SUBROUTINE READ_ROUTING_TOPO_CDF
#else
SUBROUTINE READ_ROUTING_TOPO_CDF
IMPLICIT NONE
WRITE(LOGNAM,*) 'CROUTINGNC requires compiling CaMa with UseCDF_CMF'
STOP 10
END SUBROUTINE READ_ROUTING_TOPO_CDF
#endif
SUBROUTINE READ_TOPO_BIN
USE CMF_UTILS_MOD,       ONLY: mapR2vecD, CONV_END,  INQUIRE_FID
IMPLICIT NONE
!* local variables
INTEGER(KIND=JPIM)          :: ILFP
REAL(KIND=JPRM),ALLOCATABLE :: R2TEMP(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: D2TEMP(:,:)
!================================================
ALLOCATE(R2TEMP(NX,NY))
ALLOCATE(D2TEMP(NSEQMAX,1))

TMPNAM=INQUIRE_FID()

WRITE(LOGNAM,*)'TOPO_INIT: unit-catchment area : ',TRIM(CGRAREA) 
OPEN(TMPNAM,FILE=CGRAREA,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) R2TEMP(:,:)
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
CALL mapR2vecD(R2TEMP,D2GRAREA)
CLOSE(TMPNAM)

WRITE(LOGNAM,*)'TOPO_INIT: ground elevation : ',TRIM(CELEVTN)
OPEN(TMPNAM,FILE=CELEVTN,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) R2TEMP(:,:)
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
CALL mapR2vecD(R2TEMP,D2ELEVTN)
CLOSE(TMPNAM)

WRITE(LOGNAM,*)'TOPO_INIT: downstream distance : ',TRIM(CNXTDST)
OPEN(TMPNAM,FILE=CNXTDST,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) R2TEMP(:,:)
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
CALL mapR2vecD(R2TEMP,D2NXTDST)
CLOSE(TMPNAM)

WRITE(LOGNAM,*)'TOPO_INIT: river channel length : ',TRIM(CRIVLEN)
OPEN(TMPNAM,FILE=CRIVLEN,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) R2TEMP(:,:)
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
CALL mapR2vecD(R2TEMP,D2RIVLEN)
CLOSE(TMPNAM)

WRITE(LOGNAM,*)'TOPO_INIT: floodplain elevation profile : ',TRIM(CFLDHGT)
OPEN(TMPNAM,FILE=TRIM(CFLDHGT),FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
DO ILFP=1,NLFP
  READ(TMPNAM,REC=ILFP) R2TEMP
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
  CALL mapR2vecD(R2TEMP,D2TEMP)
  D2FLDHGT(:,:,ILFP)= D2TEMP(:,:)
ENDDO
CLOSE(TMPNAM)

WRITE(LOGNAM,*)'TOPO_INIT: grid area : ',TRIM(CGRDARE)
OPEN(TMPNAM,FILE=TRIM(CGRDARE),FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) R2TEMP(:,:)
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
R2GRDARE(:,:) = R2TEMP(:,:)
CLOSE(TMPNAM)

!*** river channel / groundwater parameters)

WRITE(LOGNAM,*)'TOPO_INIT: river channel depth : ',TRIM(CRIVHGT)
OPEN(TMPNAM,FILE=CRIVHGT,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) R2TEMP(:,:)
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
CALL mapR2vecD(R2TEMP,D2RIVHGT)
CLOSE(TMPNAM)

WRITE(LOGNAM,*)'TOPO_INIT: river channel width : ',TRIM(CRIVWTH)
OPEN(TMPNAM,FILE=CRIVWTH,FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) R2TEMP(:,:)
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
CALL mapR2vecD(R2TEMP,D2RIVWTH)
CLOSE(TMPNAM)

WRITE(LOGNAM,*)'TOPO_INIT: manning coefficient river: ',TRIM(CRIVMAN)
OPEN(TMPNAM,FILE=TRIM(CRIVMAN),FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
READ(TMPNAM,REC=1) R2TEMP(:,:)
  IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
CALL mapR2vecD(R2TEMP,D2RIVMAN)
CLOSE(TMPNAM)

IF( LGDWDLY )THEN
  WRITE(LOGNAM,*)'TOPO_INIT: groundwater delay parameter: ',TRIM(CGDWDLY)
  OPEN(TMPNAM,FILE=TRIM(CGDWDLY),FORM='UNFORMATTED',ACCESS='DIRECT',RECL=4*NX*NY)
  READ(TMPNAM,REC=1) R2TEMP(:,:)
    IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
  CALL mapR2vecD(R2TEMP,D2GDWDLY)
  CLOSE(TMPNAM)
ENDIF

IF( LSLPMIX )THEN
  WRITE(LOGNAM,*)'TOPO_INIT: LSLPMIX only used in IFS, not availabke with binary map'
ENDIF
IF( LSLOPEMOUTH )THEN
  WRITE(LOGNAM,*)'TOPO_INIT: LSLOPEMOUTH only used in IFS, not availabke with binary map'
ENDIF

! ==========

IF( LMEANSL ) THEN
  WRITE(LOGNAM, *)'TOPO_INIT: mean sea level: ', TRIM(CMEANSL)
  OPEN(TMPNAM, FILE=CMEANSL, FORM='UNFORMATTED', ACCESS='DIRECT', RECL=4*NX*NY)
  READ(TMPNAM, REC=1) R2TEMP(:,:)
    IF( LMAPEND ) CALL CONV_END(R2TEMP,NX,NY)
  CALL mapR2vecD(R2TEMP, D2MEANSL)
  CLOSE(TMPNAM)
ENDIF

DEALLOCATE(R2TEMP)
DEALLOCATE(D2TEMP)

END SUBROUTINE READ_TOPO_BIN
!==========================================================
!+
!+
!+
!==========================================================
SUBROUTINE READ_TOPO_CDF
#ifdef UseCDF_CMF
USE NETCDF 
USE CMF_UTILS_MOD,            ONLY: NCERROR,mapR2vecD
USE YOS_CMF_MAP,              ONLY: D2ELEVSLOPE     !! only used in ECMWF
IMPLICIT NONE
!* local variables
INTEGER(KIND=JPIM)               :: NCID,VARID,STATUS
INTEGER(KIND=JPIM)               :: ILEV
REAL(KIND=JPRM),ALLOCATABLE      :: R2TEMP(:,:)
REAL(KIND=JPRB),ALLOCATABLE      :: D2TEMP(:,:)
!================================================
ALLOCATE(R2TEMP(NX,NY))
ALLOCATE(D2TEMP(NSEQMAX,1))

!! CLIM FILE
CALL NCERROR (NF90_OPEN(CRIVCLINC,NF90_NOWRITE,NCID),'opening '//TRIM(CRIVCLINC) )

WRITE(LOGNAM,*)'TOPO_INIT: ctmare:',TRIM(CRIVCLINC)
CALL NCERROR ( NF90_INQ_VARID(NCID,'ctmare',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' )
CALL mapR2vecD(R2TEMP,D2GRAREA)

WRITE(LOGNAM,*)'TOPO_INIT: elevtn:',TRIM(CRIVCLINC)
CALL NCERROR ( NF90_INQ_VARID(NCID,'elevtn',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
CALL mapR2vecD(R2TEMP,D2ELEVTN)

WRITE(LOGNAM,*)'TOPO_INIT: nxtdst:',TRIM(CRIVCLINC)
CALL NCERROR ( NF90_INQ_VARID(NCID,'nxtdst',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
CALL mapR2vecD(R2TEMP,D2NXTDST)

WRITE(LOGNAM,*)'TOPO_INIT: rivlen:',TRIM(CRIVCLINC)
CALL NCERROR ( NF90_INQ_VARID(NCID,'rivlen',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
CALL mapR2vecD(R2TEMP,D2RIVLEN)

WRITE(LOGNAM,*)'TOPO_INIT: fldhgt:',TRIM(CRIVCLINC)
CALL NCERROR ( NF90_INQ_VARID(NCID,'fldhgt',VARID),'getting id' )
DO ILEV=1,NLFP
  CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP,(/1,1,ILEV/),(/NX,NY,1/)),'reading data' ) 
  CALL mapR2vecD(R2TEMP,D2TEMP)
  D2FLDHGT(:,:,ILEV)=D2TEMP(:,:)
ENDDO

CALL NCERROR( NF90_CLOSE(NCID))

IF ( LSLOPEMOUTH ) THEN
  ALLOCATE( D2ELEVSLOPE(NSEQMAX,1) )
  WRITE(LOGNAM,*)'TOPO_INIT: elevslope:',TRIM(CRIVPARNC)
  STATUS = NF90_INQ_VARID(NCID,'elevslope',VARID)
  IF (STATUS /= 0 ) THEN
    WRITE(LOGNAM,*)'TOPO_INIT: elevslope: not present, aborting'
    STOP 9 
  ELSE
    CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
  ENDIF 
  CALL mapR2vecD(R2TEMP,D2ELEVSLOPE)
ENDIF

!!========== 
!! PAR FILE (river channel / groundwater parameters)
CALL NCERROR (NF90_OPEN(CRIVPARNC,NF90_NOWRITE,NCID),'opening '//TRIM(CRIVPARNC) )

WRITE(LOGNAM,*)'TOPO_INIT: rivwth:',TRIM(CRIVPARNC)
CALL NCERROR ( NF90_INQ_VARID(NCID,'rivwth',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
CALL mapR2vecD(R2TEMP,D2RIVWTH)

WRITE(LOGNAM,*)'TOPO_INIT: rivhgt:',TRIM(CRIVPARNC)
CALL NCERROR ( NF90_INQ_VARID(NCID,'rivhgt',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
CALL mapR2vecD(R2TEMP,D2RIVHGT)

WRITE(LOGNAM,*)'TOPO_INIT: rivman:',TRIM(CRIVPARNC)
CALL NCERROR ( NF90_INQ_VARID(NCID,'rivman',VARID),'getting id' )
CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
CALL mapR2vecD(R2TEMP,D2RIVMAN)

IF ( LGDWDLY ) THEN
  WRITE(LOGNAM,*)'TOPO_INIT: GDWDLY:',TRIM(CRIVPARNC)
  STATUS = NF90_INQ_VARID(NCID,'gdwdly',VARID)
  IF (STATUS /= 0 ) THEN
    WRITE(LOGNAM,*)'TOPO_INIT: GDWDLY: not present, setting to zero'
    R2TEMP(:,:) = 0._JPRB
  ELSE
    CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
  ENDIF 
  CALL mapR2vecD(R2TEMP,D2GDWDLY)
ENDIF

CALL NCERROR( NF90_CLOSE(NCID))

!!========== 
!! MEAN SEA LEVEL FILE
IF( LMEANSL ) THEN
  CALL NCERROR (NF90_OPEN(CMEANSLNC,NF90_NOWRITE,NCID),'opening '//TRIM(CMEANSLNC) )
  WRITE(LOGNAM,*)'TOPO_INIT: rivhgt:',TRIM(CMEANSLNC)
  CALL NCERROR ( NF90_INQ_VARID(NCID,'meansl',VARID),'getting id' )
  CALL NCERROR ( NF90_GET_VAR(NCID,VARID,R2TEMP),'reading data' ) 
  CALL mapR2vecD ( R2TEMP,D2MEANSL  )
  CALL NCERROR ( NF90_CLOSE(NCID) )
ENDIF 

DEALLOCATE(R2TEMP)
DEALLOCATE(D2TEMP)
#endif
END SUBROUTINE READ_TOPO_CDF
!==========================================================
!+
!+
!+
!==========================================================
SUBROUTINE SET_FLDSTG
IMPLICIT NONE
!* local variables
INTEGER(KIND=JPIM),SAVE  ::  ISEQ, I
REAL(KIND=JPRB),SAVE     ::  DSTONOW
REAL(KIND=JPRB),SAVE     ::  DSTOPRE
REAL(KIND=JPRB),SAVE     ::  DHGTPRE
REAL(KIND=JPRB),SAVE     ::  DWTHINC
!$OMP THREADPRIVATE               (I,DSTONOW,DSTOPRE,DHGTPRE,DWTHINC)
!================================================
D2FLDSTOMAX(:,:,:) = 0._JPRD
D2FLDGRD(:,:,:)    = 0._JPRB
DFRCINC=REAL(NLFP,KIND=JPRB)**(-1.)
!
!$OMP PARALLEL DO
DO ISEQ=1, NSEQMAX
  DSTOPRE = D2RIVSTOMAX(ISEQ,1)
  DHGTPRE = 0._JPRB
  DWTHINC = D2GRAREA(ISEQ,1) * D2RIVLEN(ISEQ,1)**(-1.) * DFRCINC
  DO I=1, NLFP
    DSTONOW = D2RIVLEN(ISEQ,1) * ( D2RIVWTH(ISEQ,1) + DWTHINC*(REAL(I,KIND=JPRB)-0.5) ) * (D2FLDHGT(ISEQ,1,I)-DHGTPRE)
    D2FLDSTOMAX(ISEQ,1,I) = DSTOPRE + DSTONOW
    D2FLDGRD(ISEQ,1,I) = (D2FLDHGT(ISEQ,1,I)-DHGTPRE) * DWTHINC**(-1.)
    DSTOPRE = D2FLDSTOMAX(ISEQ,1,I)
    DHGTPRE = D2FLDHGT(ISEQ,1,I)
  ENDDO
ENDDO
!$OMP END PARALLEL DO

!
END SUBROUTINE SET_FLDSTG
!==========================================================
!+
!+
!+
!==========================================================
SUBROUTINE SET_SLOPEMIX    !! only used in IFS0
#ifdef UseCDF_CMF
USE NETCDF 
USE CMF_UTILS_MOD,           ONLY: NCERROR,mapI2vecI

IMPLICIT NONE
INTEGER(KIND=JPIM),ALLOCATABLE  :: I2TEMP(:,:)
INTEGER(KIND=JPIM)              :: ISEQ, I0, I1
INTEGER(KIND=JPIM)              :: NCID,VARID,STATUS

  ALLOCATE(I2TEMP(NX,NY))
  WRITE(LOGNAM,*)'TOPO_INIT: mask_slope:',TRIM(CRIVPARNC)
  STATUS =  NF90_INQ_VARID(NCID,'mask_slope',VARID)
  IF (STATUS /= 0 ) THEN
    WRITE(LOGNAM,*)'TOPO_INIT: mask_slope: LSLPMIX should be set to FALSE: ABORTING!'
    STOP 9
  ENDIF 
  CALL NCERROR ( NF90_GET_VAR(NCID,VARID,I2TEMP),'reading data' ) 
  CALL mapI2vecI(I2TEMP,I2MASK)
  I0=0
  I1=0
  DO ISEQ=1,NSEQMAX
    IF (I2MASK(ISEQ,1) == 1 ) THEN  !! kinematic wave applied
      I1=I1+1
    ENDIF
    IF (I2MASK(ISEQ,1) == 0 ) THEN 
      I0=I0+1
    ENDIF
  ENDDO
  WRITE(LOGNAM,*)'TOPO_INIT: sum(mask==0), sum(mask==1)',I0,I1
  IF ( I0+I1 .NE. NSEQMAX ) THEN 
     WRITE(LOGNAM,*)'TOPO_INIT: mask==0 + mask == 1 does not match NSEQMAX.. something wrong, aborting'
     STOP 9
  ENDIF 

  DEALLOCATE(I2TEMP)
#endif
END SUBROUTINE SET_SLOPEMIX

END SUBROUTINE CMF_TOPO_INIT
!####################################################################


END MODULE CMF_CTRL_MAPS_MOD
